# backend/services/fault_mappings.py

UNIFIED_STATES = {
    1: "ĐANG VẬN HÀNH", 2: "CHỜ", 3: "ĐANG KHỞI ĐỘNG", 4: "ĐÃ DỪNG", 5: "LỖI",
    6: "VẬN HÀNH CÓ CẢNH BÁO", 7: "GIẢM CÔNG SUẤT", 8: "VẬN HÀNH THEO LỆNH ĐIỀU ĐỘ", 9: "LỖI TRUYỀN THÔNG",
    10: "DỪNG KHẨN CẤP", 11: "DỪNG BẰNG NÚT", 12: "CHỜ KHỞI TẠO", 13: "ĐANG DÒ LƯỚI",
    14: "KIỂM TRA CÁCH ĐIỆN", 15: "TỰ KIỂM TRA", 16: "VẬN HÀNH ĐỘC LẬP", 17: "CHẾ ĐỘ BẢO TRÌ",
    18: "ĐANG NÂNG CẤP", 19: "ĐANG TẮT", 20: "GIỚI HẠN CÔNG SUẤT", 21: "CHỜ PHỤC HỒI LƯỚI", 22: "NGỦ"
}

UNIFIED_FAULTS = {
    # LƯỚI ĐIỆN
    1001: "QUÁ ĐIỆN ÁP LƯỚI", 1002: "QUÁ ĐIỆN ÁP LƯỚI TẠM THỜI", 1003: "THẤP ĐIỆN ÁP LƯỚI",
    1004: "QUÁ DÒNG LƯỚI", 1005: "QUÁ TẦN SỐ LƯỚI", 1006: "THẤP TẦN SỐ LƯỚI",
    1007: "MẤT ĐIỆN LƯỚI", 1008: "MẤT CÂN BẰNG ĐIỆN ÁP LƯỚI", 1009: "MẤT PHA LƯỚI",
    1010: "LƯỚI BẤT THƯỜNG", 1011: "QUÁ ĐIỆN ÁP LƯỚI 10 PHÚT", 1012: "KHÁNG TRỞ LƯỚI BẤT THƯỜNG",
    1013: "CÔNG SUẤT NGƯỢC LƯỚI", 1014: "MẤT KẾT NỐI LƯỚI", 1015: "BẢO VỆ LƯỚI KÍCH HOẠT",
    # PIN MẶT TRỜI
    1101: "ĐẤU NGƯỢC PV", 1102: "QUÁ ĐIỆN ÁP PV", 1103: "LỖI CẤU HÌNH PV",
    1104: "ĐẦU VÀO PV BẤT THƯỜNG", 1105: "LỖI DÂY PV", 1106: "MẤT DÂY PV",
    1107: "DÂY PV KHÔNG CÂN BẰNG", 1108: "ĐIỆN ÁP PV THẤP", 1109: "QUÁ ĐIỆN ÁP BUS DC PV",
    1110: "THẤP ĐIỆN ÁP BUS DC PV",
    # ĐIỆN
    1201: "DÒNG RÒ", 1202: "KHÁNG TRỞ CÁCH ĐIỆN THẤP", 1203: "QUÁ TẢI AC",
    1204: "NGẮN MẠCH AC", 1205: "QUÁ DÒNG DC", 1206: "LỖI NỐI ĐẤT",
    1207: "LỖI DÒNG DƯ", 1208: "THÀNH PHẦN DC CAO", 1209: "TIÊM DC CAO",
    # NHIỆT ĐỘ
    1301: "QUÁ NHIỆT THIẾT BỊ", 1302: "QUÁ NHIỆT MÔI TRƯỜNG", 1303: "NHIỆT ĐỘ MÔI TRƯỜNG QUÁ THẤP",
    1304: "QUÁ NHIỆT TẢN NHIỆT", 1305: "QUÁ NHIỆT MODULE",
    # PHẦN CỨNG
    1401: "LỖI QUẠT", 1402: "LỖI SPD AC", 1403: "LỖI SPD DC", 1404: "LỖI RƠ LE",
    1405: "LỖI CÔNG TẮC TƠ", 1406: "LỖI CẢM BIẾN", 1407: "LỖI EEPROM",
    1408: "LỖI TRUYỀN THÔNG NỘI BỘ", 1409: "LỖI BOARD ĐIỀU KHIỂN", 1410: "LỖI MODULE CÔNG SUẤT",
    # TRUYỀN THÔNG
    1501: "LỖI TRUYỀN THÔNG", 1502: "LỖI TRUYỀN THÔNG ĐỒNG HỒ", 1503: "LỖI TRUYỀN THÔNG RS485",
    1504: "LỖI TRUYỀN THÔNG MODBUS", 1505: "LỖI TRUYỀN THÔNG ETHERNET", 1506: "LỖI TRUYỀN THÔNG CLOUD",
    # AN TOÀN
    1601: "LỖI HỒ QUANG", 1602: "VÔ HIỆU HÓA DÒ HỒ QUANG", 1603: "KÍCH HOẠT DỪNG NHANH",
    1604: "KÍCH HOẠT BẢO VỆ CHÁY", 1605: "KÍCH HOẠT DỪNG KHẨN CẤP",
    # HỆ THỐNG
    1701: "THIẾT BỊ BẤT THƯỜNG", 1702: "LỖI TỰ KIỂM BẢO VỆ LƯỚI", 1703: "LỖI TỰ KIỂM HỆ THỐNG",
    1704: "NGOẠI LỆ PHẦN MỀM", 1705: "LỖI NÂNG CẤP FIRMWARE", 1706: "LỖI CẤU HÌNH",
    # GIẢM CÔNG SUẤT
    1801: "GIẢM CÔNG SUẤT", 1802: "GIẢM CÔNG SUẤT DO NHIỆT", 1803: "GIẢM CÔNG SUẤT DO LƯỚI",
    1804: "GIẢM CÔNG SUẤT DO TẦN SỐ", 1805: "KIỂM SOÁT GIỚI HẠN CÔNG SUẤT",
}

SUNGROW_FAULT_MAP = {
    2: {'id_sungrow': 2, 'id_unified': 1001, 'name': 'Quá điện áp lưới', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra điện áp lưới, cài đặt bảo vệ, đầu phân áp máy biến áp'},
    3: {'id_sungrow': 3, 'id_unified': 1001, 'name': 'Quá điện áp lưới', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra điện áp lưới, cài đặt bảo vệ, đầu phân áp máy biến áp'},
    4: {'id_sungrow': 4, 'id_unified': 1003, 'name': 'Thấp điện áp lưới', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra điện áp lưới và kết nối'},
    5: {'id_sungrow': 5, 'id_unified': 1003, 'name': 'Thấp điện áp lưới', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra điện áp lưới và kết nối'},
    7: {'id_sungrow': 7, 'id_unified': 1702, 'name': 'Lỗi hệ thống', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra hệ thống nội bộ biến tần, liên hệ nhà sản xuất'},
    8: {'id_sungrow': 8, 'id_unified': 1005, 'name': 'Quá tần số lưới', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra tần số lưới'},
    9: {'id_sungrow': 9, 'id_unified': 1006, 'name': 'Thấp tần số lưới', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra tần số lưới'},
    10: {'id_sungrow': 10, 'id_unified': 1007, 'name': 'Mất điện lưới', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra kết nối lưới và cầu dao'},
    11: {'id_sungrow': 11, 'id_unified': 1702, 'name': 'Lỗi hệ thống', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra hệ thống nội bộ biến tần, liên hệ nhà sản xuất'},
    12: {'id_sungrow': 12, 'id_unified': 1201, 'name': 'Dòng rò', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra bảo vệ dòng rò'},
    13: {'id_sungrow': 13, 'id_unified': 1010, 'name': 'Lưới bất thường', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra chất lượng lưới điện'},
    14: {'id_sungrow': 14, 'id_unified': 1001, 'name': 'Quá điện áp lưới', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra điện áp lưới, cài đặt bảo vệ, đầu phân áp máy biến áp'},
    15: {'id_sungrow': 15, 'id_unified': 1001, 'name': 'Quá điện áp lưới', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra điện áp lưới, cài đặt bảo vệ, đầu phân áp máy biến áp'},
    16: {'id_sungrow': 16, 'id_unified': 1702, 'name': 'Lỗi hệ thống', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra hệ thống nội bộ biến tần, liên hệ nhà sản xuất'},
    17: {'id_sungrow': 17, 'id_unified': 1008, 'name': 'Mất cân bằng điện áp lưới', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra cân bằng pha'},
    19: {'id_sungrow': 19, 'id_unified': 1702, 'name': 'Lỗi hệ thống', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra hệ thống nội bộ biến tần, liên hệ nhà sản xuất'},
    20: {'id_sungrow': 20, 'id_unified': 1702, 'name': 'Lỗi hệ thống', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra hệ thống nội bộ biến tần, liên hệ nhà sản xuất'},
    21: {'id_sungrow': 21, 'id_unified': 1702, 'name': 'Lỗi hệ thống', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra hệ thống nội bộ biến tần, liên hệ nhà sản xuất'},
    22: {'id_sungrow': 22, 'id_unified': 1702, 'name': 'Lỗi hệ thống', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra hệ thống nội bộ biến tần, liên hệ nhà sản xuất'},
    23: {'id_sungrow': 23, 'id_unified': 1702, 'name': 'Lỗi hệ thống', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra hệ thống nội bộ biến tần, liên hệ nhà sản xuất'},
    24: {'id_sungrow': 24, 'id_unified': 1702, 'name': 'Lỗi hệ thống', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra hệ thống nội bộ biến tần, liên hệ nhà sản xuất'},
    25: {'id_sungrow': 25, 'id_unified': 1702, 'name': 'Lỗi hệ thống', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra hệ thống nội bộ biến tần, liên hệ nhà sản xuất'},
    28: {'id_sungrow': 28, 'id_unified': 1101, 'name': 'Đấu ngược PV 1', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra cực tính và dây nối PV'},
    29: {'id_sungrow': 29, 'id_unified': 1101, 'name': 'Đấu ngược PV 2', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra cực tính và dây nối PV'},
    30: {'id_sungrow': 30, 'id_unified': 1702, 'name': 'Lỗi hệ thống', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra hệ thống nội bộ biến tần, liên hệ nhà sản xuất'},
    31: {'id_sungrow': 31, 'id_unified': 1702, 'name': 'Lỗi hệ thống', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra hệ thống nội bộ biến tần, liên hệ nhà sản xuất'},
    32: {'id_sungrow': 32, 'id_unified': 1702, 'name': 'Lỗi hệ thống', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra hệ thống nội bộ biến tần, liên hệ nhà sản xuất'},
    33: {'id_sungrow': 33, 'id_unified': 1702, 'name': 'Lỗi hệ thống', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra hệ thống nội bộ biến tần, liên hệ nhà sản xuất'},
    34: {'id_sungrow': 34, 'id_unified': 1702, 'name': 'Lỗi hệ thống', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra hệ thống nội bộ biến tần, liên hệ nhà sản xuất'},
    36: {'id_sungrow': 36, 'id_unified': 1702, 'name': 'Lỗi hệ thống', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra hệ thống nội bộ biến tần, liên hệ nhà sản xuất'},
    37: {'id_sungrow': 37, 'id_unified': 1302, 'name': 'Quá nhiệt môi trường', 'severity': 'WARNING', 'repair_instruction': 'Kiểm tra làm mát và thông gió'},
    38: {'id_sungrow': 38, 'id_unified': 1702, 'name': 'Lỗi hệ thống', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra hệ thống nội bộ biến tần, liên hệ nhà sản xuất'},
    39: {'id_sungrow': 39, 'id_unified': 1202, 'name': 'Kháng trở cách điện thấp', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra kháng trở cách điện'},
    40: {'id_sungrow': 40, 'id_unified': 1702, 'name': 'Lỗi hệ thống', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra hệ thống nội bộ biến tần, liên hệ nhà sản xuất'},
    41: {'id_sungrow': 41, 'id_unified': 1702, 'name': 'Lỗi hệ thống', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra hệ thống nội bộ biến tần, liên hệ nhà sản xuất'},
    42: {'id_sungrow': 42, 'id_unified': 1702, 'name': 'Lỗi hệ thống', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra hệ thống nội bộ biến tần, liên hệ nhà sản xuất'},
    43: {'id_sungrow': 43, 'id_unified': 1303, 'name': 'Nhiệt độ môi trường quá thấp', 'severity': 'WARNING', 'repair_instruction': 'Kiểm tra môi trường'},
    44: {'id_sungrow': 44, 'id_unified': 1702, 'name': 'Lỗi hệ thống', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra hệ thống nội bộ biến tần, liên hệ nhà sản xuất'},
    45: {'id_sungrow': 45, 'id_unified': 1702, 'name': 'Lỗi hệ thống', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra hệ thống nội bộ biến tần, liên hệ nhà sản xuất'},
    46: {'id_sungrow': 46, 'id_unified': 1702, 'name': 'Lỗi hệ thống', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra hệ thống nội bộ biến tần, liên hệ nhà sản xuất'},
    47: {'id_sungrow': 47, 'id_unified': 1702, 'name': 'Lỗi hệ thống', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra hệ thống nội bộ biến tần, liên hệ nhà sản xuất'},
    48: {'id_sungrow': 48, 'id_unified': 1702, 'name': 'Lỗi hệ thống', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra hệ thống nội bộ biến tần, liên hệ nhà sản xuất'},
    49: {'id_sungrow': 49, 'id_unified': 1702, 'name': 'Lỗi hệ thống', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra hệ thống nội bộ biến tần, liên hệ nhà sản xuất'},
    50: {'id_sungrow': 50, 'id_unified': 1702, 'name': 'Lỗi hệ thống', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra hệ thống nội bộ biến tần, liên hệ nhà sản xuất'},
    52: {'id_sungrow': 52, 'id_unified': 1702, 'name': 'Lỗi hệ thống', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra hệ thống nội bộ biến tần, liên hệ nhà sản xuất'},
    53: {'id_sungrow': 53, 'id_unified': 1702, 'name': 'Lỗi hệ thống', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra hệ thống nội bộ biến tần, liên hệ nhà sản xuất'},
    54: {'id_sungrow': 54, 'id_unified': 1702, 'name': 'Lỗi hệ thống', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra hệ thống nội bộ biến tần, liên hệ nhà sản xuất'},
    55: {'id_sungrow': 55, 'id_unified': 1702, 'name': 'Lỗi hệ thống', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra hệ thống nội bộ biến tần, liên hệ nhà sản xuất'},
    56: {'id_sungrow': 56, 'id_unified': 1702, 'name': 'Lỗi hệ thống', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra hệ thống nội bộ biến tần, liên hệ nhà sản xuất'},
    57: {'id_sungrow': 57, 'id_unified': 1702, 'name': 'Lỗi hệ thống', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra hệ thống nội bộ biến tần, liên hệ nhà sản xuất'},
    58: {'id_sungrow': 58, 'id_unified': 1702, 'name': 'Lỗi hệ thống', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra hệ thống nội bộ biến tần, liên hệ nhà sản xuất'},
    59: {'id_sungrow': 59, 'id_unified': 1703, 'name': 'Cảnh báo hệ thống', 'severity': 'WARNING', 'repair_instruction': 'Kiểm tra chi tiết cảnh báo'},
    60: {'id_sungrow': 60, 'id_unified': 1702, 'name': 'Lỗi hệ thống', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra hệ thống nội bộ biến tần, liên hệ nhà sản xuất'},
    61: {'id_sungrow': 61, 'id_unified': 1702, 'name': 'Lỗi hệ thống', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra hệ thống nội bộ biến tần, liên hệ nhà sản xuất'},
    62: {'id_sungrow': 62, 'id_unified': 1702, 'name': 'Lỗi hệ thống', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra hệ thống nội bộ biến tần, liên hệ nhà sản xuất'},
    63: {'id_sungrow': 63, 'id_unified': 1702, 'name': 'Lỗi hệ thống', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra hệ thống nội bộ biến tần, liên hệ nhà sản xuất'},
    64: {'id_sungrow': 64, 'id_unified': 1702, 'name': 'Lỗi hệ thống', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra hệ thống nội bộ biến tần, liên hệ nhà sản xuất'},
    65: {'id_sungrow': 65, 'id_unified': 1702, 'name': 'Lỗi hệ thống', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra hệ thống nội bộ biến tần, liên hệ nhà sản xuất'},
    66: {'id_sungrow': 66, 'id_unified': 1702, 'name': 'Lỗi hệ thống', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra hệ thống nội bộ biến tần, liên hệ nhà sản xuất'},
    67: {'id_sungrow': 67, 'id_unified': 1702, 'name': 'Lỗi hệ thống', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra hệ thống nội bộ biến tần, liên hệ nhà sản xuất'},
    68: {'id_sungrow': 68, 'id_unified': 1702, 'name': 'Lỗi hệ thống', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra hệ thống nội bộ biến tần, liên hệ nhà sản xuất'},
    70: {'id_sungrow': 70, 'id_unified': 1703, 'name': 'Cảnh báo hệ thống', 'severity': 'WARNING', 'repair_instruction': 'Kiểm tra chi tiết cảnh báo'},
    71: {'id_sungrow': 71, 'id_unified': 1703, 'name': 'Cảnh báo hệ thống', 'severity': 'WARNING', 'repair_instruction': 'Kiểm tra chi tiết cảnh báo'},
    72: {'id_sungrow': 72, 'id_unified': 1703, 'name': 'Cảnh báo hệ thống', 'severity': 'WARNING', 'repair_instruction': 'Kiểm tra chi tiết cảnh báo'},
    74: {'id_sungrow': 74, 'id_unified': 1703, 'name': 'Cảnh báo hệ thống', 'severity': 'WARNING', 'repair_instruction': 'Kiểm tra chi tiết cảnh báo'},
    75: {'id_sungrow': 75, 'id_unified': 1501, 'name': 'Lỗi truyền thông', 'severity': 'DISCONNECT', 'repair_instruction': 'Kiểm tra RS485 / mạng'},
    76: {'id_sungrow': 76, 'id_unified': 1703, 'name': 'Cảnh báo hệ thống', 'severity': 'WARNING', 'repair_instruction': 'Kiểm tra chi tiết cảnh báo'},
    77: {'id_sungrow': 77, 'id_unified': 1703, 'name': 'Cảnh báo hệ thống', 'severity': 'WARNING', 'repair_instruction': 'Kiểm tra chi tiết cảnh báo'},
    78: {'id_sungrow': 78, 'id_unified': 1703, 'name': 'Cảnh báo hệ thống', 'severity': 'WARNING', 'repair_instruction': 'Kiểm tra chi tiết cảnh báo'},
    79: {'id_sungrow': 79, 'id_unified': 1703, 'name': 'Cảnh báo hệ thống', 'severity': 'WARNING', 'repair_instruction': 'Kiểm tra chi tiết cảnh báo'},
    80: {'id_sungrow': 80, 'id_unified': 1703, 'name': 'Cảnh báo hệ thống', 'severity': 'WARNING', 'repair_instruction': 'Kiểm tra chi tiết cảnh báo'},
    81: {'id_sungrow': 81, 'id_unified': 1703, 'name': 'Cảnh báo hệ thống', 'severity': 'WARNING', 'repair_instruction': 'Kiểm tra chi tiết cảnh báo'},
    82: {'id_sungrow': 82, 'id_unified': 1703, 'name': 'Cảnh báo hệ thống', 'severity': 'WARNING', 'repair_instruction': 'Kiểm tra chi tiết cảnh báo'},
    83: {'id_sungrow': 83, 'id_unified': 1703, 'name': 'Cảnh báo hệ thống', 'severity': 'WARNING', 'repair_instruction': 'Kiểm tra chi tiết cảnh báo'},
    85: {'id_sungrow': 85, 'id_unified': 1702, 'name': 'Lỗi hệ thống', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra hệ thống nội bộ biến tần, liên hệ nhà sản xuất'},
    87: {'id_sungrow': 87, 'id_unified': 1702, 'name': 'Lỗi hệ thống', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra hệ thống nội bộ biến tần, liên hệ nhà sản xuất'},
    88: {'id_sungrow': 88, 'id_unified': 1601, 'name': 'Lỗi hồ quang DC', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra phóng hồ quang DC'},
    89: {'id_sungrow': 89, 'id_unified': 1703, 'name': 'Cảnh báo hệ thống', 'severity': 'WARNING', 'repair_instruction': 'Kiểm tra chi tiết cảnh báo'},
    92: {'id_sungrow': 92, 'id_unified': 1702, 'name': 'Lỗi hệ thống', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra hệ thống nội bộ biến tần, liên hệ nhà sản xuất'},
    93: {'id_sungrow': 93, 'id_unified': 1702, 'name': 'Lỗi hệ thống', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra hệ thống nội bộ biến tần, liên hệ nhà sản xuất'},
    100: {'id_sungrow': 100, 'id_unified': 1702, 'name': 'Lỗi hệ thống', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra hệ thống nội bộ biến tần, liên hệ nhà sản xuất'},
    101: {'id_sungrow': 101, 'id_unified': 1702, 'name': 'Lỗi hệ thống', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra hệ thống nội bộ biến tần, liên hệ nhà sản xuất'},
    102: {'id_sungrow': 102, 'id_unified': 1702, 'name': 'Lỗi hệ thống', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra hệ thống nội bộ biến tần, liên hệ nhà sản xuất'},
    103: {'id_sungrow': 103, 'id_unified': 1702, 'name': 'Lỗi hệ thống', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra hệ thống nội bộ biến tần, liên hệ nhà sản xuất'},
    104: {'id_sungrow': 104, 'id_unified': 1702, 'name': 'Lỗi hệ thống', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra hệ thống nội bộ biến tần, liên hệ nhà sản xuất'},
    105: {'id_sungrow': 105, 'id_unified': 1702, 'name': 'Lỗi hệ thống', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra hệ thống nội bộ biến tần, liên hệ nhà sản xuất'},
    106: {'id_sungrow': 106, 'id_unified': 1702, 'name': 'Lỗi hệ thống', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra hệ thống nội bộ biến tần, liên hệ nhà sản xuất'},
    107: {'id_sungrow': 107, 'id_unified': 1702, 'name': 'Lỗi hệ thống', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra hệ thống nội bộ biến tần, liên hệ nhà sản xuất'},
    108: {'id_sungrow': 108, 'id_unified': 1702, 'name': 'Lỗi hệ thống', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra hệ thống nội bộ biến tần, liên hệ nhà sản xuất'},
    109: {'id_sungrow': 109, 'id_unified': 1702, 'name': 'Lỗi hệ thống', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra hệ thống nội bộ biến tần, liên hệ nhà sản xuất'},
    110: {'id_sungrow': 110, 'id_unified': 1702, 'name': 'Lỗi hệ thống', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra hệ thống nội bộ biến tần, liên hệ nhà sản xuất'},
    111: {'id_sungrow': 111, 'id_unified': 1702, 'name': 'Lỗi hệ thống', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra hệ thống nội bộ biến tần, liên hệ nhà sản xuất'},
    112: {'id_sungrow': 112, 'id_unified': 1702, 'name': 'Lỗi hệ thống', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra hệ thống nội bộ biến tần, liên hệ nhà sản xuất'},
    113: {'id_sungrow': 113, 'id_unified': 1702, 'name': 'Lỗi hệ thống', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra hệ thống nội bộ biến tần, liên hệ nhà sản xuất'},
    114: {'id_sungrow': 114, 'id_unified': 1702, 'name': 'Lỗi hệ thống', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra hệ thống nội bộ biến tần, liên hệ nhà sản xuất'},
    115: {'id_sungrow': 115, 'id_unified': 1702, 'name': 'Lỗi hệ thống', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra hệ thống nội bộ biến tần, liên hệ nhà sản xuất'},
    116: {'id_sungrow': 116, 'id_unified': 1702, 'name': 'Lỗi hệ thống', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra hệ thống nội bộ biến tần, liên hệ nhà sản xuất'},
    117: {'id_sungrow': 117, 'id_unified': 1702, 'name': 'Lỗi hệ thống', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra hệ thống nội bộ biến tần, liên hệ nhà sản xuất'},
    118: {'id_sungrow': 118, 'id_unified': 1702, 'name': 'Lỗi hệ thống', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra hệ thống nội bộ biến tần, liên hệ nhà sản xuất'},
    119: {'id_sungrow': 119, 'id_unified': 1702, 'name': 'Lỗi hệ thống', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra hệ thống nội bộ biến tần, liên hệ nhà sản xuất'},
    120: {'id_sungrow': 120, 'id_unified': 1702, 'name': 'Lỗi hệ thống', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra hệ thống nội bộ biến tần, liên hệ nhà sản xuất'},
    121: {'id_sungrow': 121, 'id_unified': 1702, 'name': 'Lỗi hệ thống', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra hệ thống nội bộ biến tần, liên hệ nhà sản xuất'},
    122: {'id_sungrow': 122, 'id_unified': 1702, 'name': 'Lỗi hệ thống', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra hệ thống nội bộ biến tần, liên hệ nhà sản xuất'},
    123: {'id_sungrow': 123, 'id_unified': 1702, 'name': 'Lỗi hệ thống', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra hệ thống nội bộ biến tần, liên hệ nhà sản xuất'},
    124: {'id_sungrow': 124, 'id_unified': 1702, 'name': 'Lỗi hệ thống', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra hệ thống nội bộ biến tần, liên hệ nhà sản xuất'},
    200: {'id_sungrow': 200, 'id_unified': 1702, 'name': 'Lỗi hệ thống', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra hệ thống nội bộ biến tần, liên hệ nhà sản xuất'},
    201: {'id_sungrow': 201, 'id_unified': 1702, 'name': 'Lỗi hệ thống', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra hệ thống nội bộ biến tần, liên hệ nhà sản xuất'},
    202: {'id_sungrow': 202, 'id_unified': 1702, 'name': 'Lỗi hệ thống', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra hệ thống nội bộ biến tần, liên hệ nhà sản xuất'},
    203: {'id_sungrow': 203, 'id_unified': 1702, 'name': 'Lỗi hệ thống', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra hệ thống nội bộ biến tần, liên hệ nhà sản xuất'},
    204: {'id_sungrow': 204, 'id_unified': 1702, 'name': 'Lỗi hệ thống', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra hệ thống nội bộ biến tần, liên hệ nhà sản xuất'},
    205: {'id_sungrow': 205, 'id_unified': 1702, 'name': 'Lỗi hệ thống', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra hệ thống nội bộ biến tần, liên hệ nhà sản xuất'},
    206: {'id_sungrow': 206, 'id_unified': 1702, 'name': 'Lỗi hệ thống', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra hệ thống nội bộ biến tần, liên hệ nhà sản xuất'},
    207: {'id_sungrow': 207, 'id_unified': 1702, 'name': 'Lỗi hệ thống', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra hệ thống nội bộ biến tần, liên hệ nhà sản xuất'},
    208: {'id_sungrow': 208, 'id_unified': 1702, 'name': 'Đấu ngược PV 1', 'severity':'ERROR', 'repair_instruction': 'Kiểm tra cực tính và dây nối PV 1'},
    209: {'id_sungrow': 209, 'id_unified': 1702, 'name': 'Lỗi hệ thống', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra hệ thống nội bộ biến tần, liên hệ nhà sản xuất'},
    210: {'id_sungrow': 210, 'id_unified': 1702, 'name': 'Lỗi hệ thống', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra hệ thống nội bộ biến tần, liên hệ nhà sản xuất'},
    211: {'id_sungrow': 211, 'id_unified': 1702, 'name': 'Lỗi hệ thống', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra hệ thống nội bộ biến tần, liên hệ nhà sản xuất'},
    216: {'id_sungrow': 216, 'id_unified': 1703, 'name': 'Cảnh báo hệ thống', 'severity': 'WARNING', 'repair_instruction': 'Kiểm tra chi tiết cảnh báo'},
    217: {'id_sungrow': 217, 'id_unified': 1703, 'name': 'Cảnh báo hệ thống', 'severity': 'WARNING', 'repair_instruction': 'Kiểm tra chi tiết cảnh báo'},
    218: {'id_sungrow': 218, 'id_unified': 1703, 'name': 'Cảnh báo hệ thống', 'severity': 'WARNING', 'repair_instruction': 'Kiểm tra chi tiết cảnh báo'},
    219: {'id_sungrow': 219, 'id_unified': 1703, 'name': 'Cảnh báo hệ thống', 'severity': 'WARNING', 'repair_instruction': 'Kiểm tra chi tiết cảnh báo'},
    220: {'id_sungrow': 220, 'id_unified': 1703, 'name': 'Cảnh báo hệ thống', 'severity': 'WARNING', 'repair_instruction': 'Kiểm tra chi tiết cảnh báo'},
    221: {'id_sungrow': 221, 'id_unified': 1703, 'name': 'Cảnh báo hệ thống', 'severity': 'WARNING', 'repair_instruction': 'Kiểm tra chi tiết cảnh báo'},
    222: {'id_sungrow': 222, 'id_unified': 1703, 'name': 'Cảnh báo hệ thống', 'severity': 'WARNING', 'repair_instruction': 'Kiểm tra chi tiết cảnh báo'},
    223: {'id_sungrow': 223, 'id_unified': 1703, 'name': 'Cảnh báo hệ thống', 'severity': 'WARNING', 'repair_instruction': 'Kiểm tra chi tiết cảnh báo'},
    224: {'id_sungrow': 224, 'id_unified': 1703, 'name': 'Cảnh báo hệ thống', 'severity': 'WARNING', 'repair_instruction': 'Kiểm tra chi tiết cảnh báo'},
    225: {'id_sungrow': 225, 'id_unified': 1703, 'name': 'Cảnh báo hệ thống', 'severity': 'WARNING', 'repair_instruction': 'Kiểm tra chi tiết cảnh báo'},
    226: {'id_sungrow': 226, 'id_unified': 1703, 'name': 'Cảnh báo hệ thống', 'severity': 'WARNING', 'repair_instruction': 'Kiểm tra chi tiết cảnh báo'},
    227: {'id_sungrow': 227, 'id_unified': 1703, 'name': 'Cảnh báo hệ thống', 'severity': 'WARNING', 'repair_instruction': 'Kiểm tra chi tiết cảnh báo'},
    228: {'id_sungrow': 228, 'id_unified': 1703, 'name': 'Cảnh báo hệ thống', 'severity': 'WARNING', 'repair_instruction': 'Kiểm tra chi tiết cảnh báo'},
    229: {'id_sungrow': 229, 'id_unified': 1703, 'name': 'Cảnh báo hệ thống', 'severity': 'WARNING', 'repair_instruction': 'Kiểm tra chi tiết cảnh báo'},
    230: {'id_sungrow': 230, 'id_unified': 1703, 'name': 'Cảnh báo hệ thống', 'severity': 'WARNING', 'repair_instruction': 'Kiểm tra chi tiết cảnh báo'},
    231: {'id_sungrow': 231, 'id_unified': 1703, 'name': 'Cảnh báo hệ thống', 'severity': 'WARNING', 'repair_instruction': 'Kiểm tra chi tiết cảnh báo'},
    248: {'id_sungrow': 248, 'id_unified': 1702, 'name': 'Lỗi hệ thống', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra hệ thống nội bộ biến tần, liên hệ nhà sản xuất'},
    249: {'id_sungrow': 249, 'id_unified': 1702, 'name': 'Lỗi hệ thống', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra hệ thống nội bộ biến tần, liên hệ nhà sản xuất'},
    250: {'id_sungrow': 250, 'id_unified': 1702, 'name': 'Lỗi hệ thống', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra hệ thống nội bộ biến tần, liên hệ nhà sản xuất'},
    251: {'id_sungrow': 251, 'id_unified': 1702, 'name': 'Lỗi hệ thống', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra hệ thống nội bộ biến tần, liên hệ nhà sản xuất'},
    252: {'id_sungrow': 252, 'id_unified': 1702, 'name': 'Lỗi hệ thống', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra hệ thống nội bộ biến tần, liên hệ nhà sản xuất'},
    253: {'id_sungrow': 253, 'id_unified': 1702, 'name': 'Lỗi hệ thống', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra hệ thống nội bộ biến tần, liên hệ nhà sản xuất'},
    254: {'id_sungrow': 254, 'id_unified': 1702, 'name': 'Lỗi hệ thống', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra hệ thống nội bộ biến tần, liên hệ nhà sản xuất'},
    255: {'id_sungrow': 255, 'id_unified': 1702, 'name': 'Lỗi hệ thống', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra hệ thống nội bộ biến tần, liên hệ nhà sản xuất'},
    264: {'id_sungrow': 264, 'id_unified': 1107, 'name': 'Lỗi ngược cực đầu vào MPPT', 'severity': 'WARNING', 'repair_instruction': 'Kiểm tra lệch dòng giữa các dây'},
    265: {'id_sungrow': 265, 'id_unified': 1107, 'name': 'Lỗi ngược cực đầu vào MPPT', 'severity': 'WARNING', 'repair_instruction': 'Kiểm tra lệch dòng giữa các dây'},
    266: {'id_sungrow': 266, 'id_unified': 1107, 'name': 'Lỗi ngược cực đầu vào MPPT', 'severity': 'WARNING', 'repair_instruction': 'Kiểm tra lệch dòng giữa các dây'},
    267: {'id_sungrow': 267, 'id_unified': 1107, 'name': 'Lỗi ngược cực đầu vào MPPT', 'severity': 'WARNING', 'repair_instruction': 'Kiểm tra lệch dòng giữa các dây'},
    268: {'id_sungrow': 268, 'id_unified': 1107, 'name': 'Lỗi ngược cực đầu vào MPPT', 'severity': 'WARNING', 'repair_instruction': 'Kiểm tra lệch dòng giữa các dây'},
    269: {'id_sungrow': 269, 'id_unified': 1107, 'name': 'Lỗi ngược cực đầu vào MPPT', 'severity': 'WARNING', 'repair_instruction': 'Kiểm tra lệch dòng giữa các dây'},
    270: {'id_sungrow': 270, 'id_unified': 1107, 'name': 'Lỗi ngược cực đầu vào MPPT', 'severity': 'WARNING', 'repair_instruction': 'Kiểm tra lệch dòng giữa các dây'},
    271: {'id_sungrow': 271, 'id_unified': 1107, 'name': 'Lỗi ngược cực đầu vào MPPT', 'severity': 'WARNING', 'repair_instruction': 'Kiểm tra lệch dòng giữa các dây'},
    272: {'id_sungrow': 272, 'id_unified': 1107, 'name': 'Lỗi ngược cực đầu vào MPPT', 'severity': 'WARNING', 'repair_instruction': 'Kiểm tra lệch dòng giữa các dây'},
    273: {'id_sungrow': 273, 'id_unified': 1107, 'name': 'Lỗi ngược cực đầu vào MPPT', 'severity': 'WARNING', 'repair_instruction': 'Kiểm tra lệch dòng giữa các dây'},
    274: {'id_sungrow': 274, 'id_unified': 1107, 'name': 'Lỗi ngược cực đầu vào MPPT', 'severity': 'WARNING', 'repair_instruction': 'Kiểm tra lệch dòng giữa các dây'},
    275: {'id_sungrow': 275, 'id_unified': 1107, 'name': 'Lỗi ngược cực đầu vào MPPT', 'severity': 'WARNING', 'repair_instruction': 'Kiểm tra lệch dòng giữa các dây'},
    276: {'id_sungrow': 276, 'id_unified': 1107, 'name': 'Lỗi ngược cực đầu vào MPPT', 'severity': 'WARNING', 'repair_instruction': 'Kiểm tra lệch dòng giữa các dây'},
    277: {'id_sungrow': 277, 'id_unified': 1107, 'name': 'Lỗi ngược cực đầu vào MPPT', 'severity': 'WARNING', 'repair_instruction': 'Kiểm tra lệch dòng giữa các dây'},
    278: {'id_sungrow': 278, 'id_unified': 1107, 'name': 'Lỗi ngược cực đầu vào MPPT', 'severity': 'WARNING', 'repair_instruction': 'Kiểm tra lệch dòng giữa các dây'},
    279: {'id_sungrow': 279, 'id_unified': 1107, 'name': 'Lỗi ngược cực đầu vào MPPT', 'severity': 'WARNING', 'repair_instruction': 'Kiểm tra lệch dòng giữa các dây'},
    280: {'id_sungrow': 280, 'id_unified': 1107, 'name': 'Lỗi ngược cực đầu vào MPPT', 'severity': 'WARNING', 'repair_instruction': 'Kiểm tra lệch dòng giữa các dây'},
    281: {'id_sungrow': 281, 'id_unified': 1107, 'name': 'Lỗi ngược cực đầu vào MPPT', 'severity': 'WARNING', 'repair_instruction': 'Kiểm tra lệch dòng giữa các dây'},
    282: {'id_sungrow': 282, 'id_unified': 1107, 'name': 'Lỗi ngược cực đầu vào MPPT', 'severity': 'WARNING', 'repair_instruction': 'Kiểm tra lệch dòng giữa các dây'},
    283: {'id_sungrow': 283, 'id_unified': 1107, 'name': 'Lỗi ngược cực đầu vào MPPT', 'severity': 'WARNING', 'repair_instruction': 'Kiểm tra lệch dòng giữa các dây'},
    300: {'id_sungrow': 300, 'id_unified': 1702, 'name': 'Lỗi hệ thống', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra hệ thống nội bộ biến tần, liên hệ nhà sản xuất'},
    301: {'id_sungrow': 301, 'id_unified': 1702, 'name': 'Lỗi hệ thống', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra hệ thống nội bộ biến tần, liên hệ nhà sản xuất'},
    302: {'id_sungrow': 302, 'id_unified': 1702, 'name': 'Lỗi hệ thống', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra hệ thống nội bộ biến tần, liên hệ nhà sản xuất'},
    303: {'id_sungrow': 303, 'id_unified': 1702, 'name': 'Lỗi hệ thống', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra hệ thống nội bộ biến tần, liên hệ nhà sản xuất'},
    304: {'id_sungrow': 304, 'id_unified': 1702, 'name': 'Lỗi hệ thống', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra hệ thống nội bộ biến tần, liên hệ nhà sản xuất'},
    305: {'id_sungrow': 305, 'id_unified': 1702, 'name': 'Lỗi hệ thống', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra hệ thống nội bộ biến tần, liên hệ nhà sản xuất'},
    306: {'id_sungrow': 306, 'id_unified': 1702, 'name': 'Lỗi hệ thống', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra hệ thống nội bộ biến tần, liên hệ nhà sản xuất'},
    307: {'id_sungrow': 307, 'id_unified': 1702, 'name': 'Lỗi hệ thống', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra hệ thống nội bộ biến tần, liên hệ nhà sản xuất'},
    308: {'id_sungrow': 308, 'id_unified': 1702, 'name': 'Lỗi hệ thống', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra hệ thống nội bộ biến tần, liên hệ nhà sản xuất'},
    309: {'id_sungrow': 309, 'id_unified': 1702, 'name': 'Lỗi hệ thống', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra hệ thống nội bộ biến tần, liên hệ nhà sản xuất'},
    310: {'id_sungrow': 310, 'id_unified': 1702, 'name': 'Lỗi hệ thống', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra hệ thống nội bộ biến tần, liên hệ nhà sản xuất'},
    311: {'id_sungrow': 311, 'id_unified': 1702, 'name': 'Lỗi hệ thống', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra hệ thống nội bộ biến tần, liên hệ nhà sản xuất'},
    312: {'id_sungrow': 312, 'id_unified': 1702, 'name': 'Lỗi hệ thống', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra hệ thống nội bộ biến tần, liên hệ nhà sản xuất'},
    313: {'id_sungrow': 313, 'id_unified': 1702, 'name': 'Lỗi hệ thống', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra hệ thống nội bộ biến tần, liên hệ nhà sản xuất'},
    314: {'id_sungrow': 314, 'id_unified': 1702, 'name': 'Lỗi hệ thống', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra hệ thống nội bộ biến tần, liên hệ nhà sản xuất'},
    315: {'id_sungrow': 315, 'id_unified': 1702, 'name': 'Lỗi hệ thống', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra hệ thống nội bộ biến tần, liên hệ nhà sản xuất'},
    316: {'id_sungrow': 316, 'id_unified': 1702, 'name': 'Lỗi hệ thống', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra hệ thống nội bộ biến tần, liên hệ nhà sản xuất'},
    317: {'id_sungrow': 317, 'id_unified': 1702, 'name': 'Lỗi hệ thống', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra hệ thống nội bộ biến tần, liên hệ nhà sản xuất'},
    318: {'id_sungrow': 318, 'id_unified': 1702, 'name': 'Lỗi hệ thống', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra hệ thống nội bộ biến tần, liên hệ nhà sản xuất'},
    319: {'id_sungrow': 319, 'id_unified': 1702, 'name': 'Lỗi hệ thống', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra hệ thống nội bộ biến tần, liên hệ nhà sản xuất'},
    320: {'id_sungrow': 320, 'id_unified': 1702, 'name': 'Lỗi hệ thống', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra hệ thống nội bộ biến tần, liên hệ nhà sản xuất'},
    321: {'id_sungrow': 321, 'id_unified': 1702, 'name': 'Lỗi hệ thống', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra hệ thống nội bộ biến tần, liên hệ nhà sản xuất'},
    322: {'id_sungrow': 322, 'id_unified': 1702, 'name': 'Lỗi hệ thống', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra hệ thống nội bộ biến tần, liên hệ nhà sản xuất'},
    323: {'id_sungrow': 323, 'id_unified': 1702, 'name': 'Lỗi hệ thống', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra hệ thống nội bộ biến tần, liên hệ nhà sản xuất'},
    324: {'id_sungrow': 324, 'id_unified': 1702, 'name': 'Lỗi hệ thống', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra hệ thống nội bộ biến tần, liên hệ nhà sản xuất'},
    325: {'id_sungrow': 325, 'id_unified': 1702, 'name': 'Lỗi hệ thống', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra hệ thống nội bộ biến tần, liên hệ nhà sản xuất'},
    326: {'id_sungrow': 326, 'id_unified': 1702, 'name': 'Lỗi hệ thống', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra hệ thống nội bộ biến tần, liên hệ nhà sản xuất'},
    401: {'id_sungrow': 401, 'id_unified': 1702, 'name': 'Lỗi hệ thống', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra hệ thống nội bộ biến tần, liên hệ nhà sản xuất'},
    402: {'id_sungrow': 402, 'id_unified': 1702, 'name': 'Lỗi hệ thống', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra hệ thống nội bộ biến tần, liên hệ nhà sản xuất'},
    403: {'id_sungrow': 403, 'id_unified': 1702, 'name': 'Lỗi hệ thống', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra hệ thống nội bộ biến tần, liên hệ nhà sản xuất'},
    404: {'id_sungrow': 404, 'id_unified': 1702, 'name': 'Lỗi hệ thống', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra hệ thống nội bộ biến tần, liên hệ nhà sản xuất'},
    405: {'id_sungrow': 405, 'id_unified': 1702, 'name': 'Lỗi hệ thống', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra hệ thống nội bộ biến tần, liên hệ nhà sản xuất'},
    406: {'id_sungrow': 406, 'id_unified': 1702, 'name': 'Lỗi hệ thống', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra hệ thống nội bộ biến tần, liên hệ nhà sản xuất'},
    407: {'id_sungrow': 407, 'id_unified': 1702, 'name': 'Lỗi hệ thống', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra hệ thống nội bộ biến tần, liên hệ nhà sản xuất'},
    408: {'id_sungrow': 408, 'id_unified': 1702, 'name': 'Lỗi hệ thống', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra hệ thống nội bộ biến tần, liên hệ nhà sản xuất'},
    409: {'id_sungrow': 409, 'id_unified': 1702, 'name': 'Lỗi hệ thống', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra hệ thống nội bộ biến tần, liên hệ nhà sản xuất'},
    410: {'id_sungrow': 410, 'id_unified': 1702, 'name': 'Lỗi hệ thống', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra hệ thống nội bộ biến tần, liên hệ nhà sản xuất'},
    411: {'id_sungrow': 411, 'id_unified': 1702, 'name': 'Lỗi hệ thống', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra hệ thống nội bộ biến tần, liên hệ nhà sản xuất'},
    412: {'id_sungrow': 412, 'id_unified': 1702, 'name': 'Lỗi hệ thống', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra hệ thống nội bộ biến tần, liên hệ nhà sản xuất'},
    432: {'id_sungrow': 432, 'id_unified': 1703, 'name': 'Cảnh báo hệ thống', 'severity': 'WARNING', 'repair_instruction': 'Kiểm tra chi tiết cảnh báo'},
    433: {'id_sungrow': 433, 'id_unified': 1703, 'name': 'Cảnh báo hệ thống', 'severity': 'WARNING', 'repair_instruction': 'Kiểm tra chi tiết cảnh báo'},
    434: {'id_sungrow': 434, 'id_unified': 1703, 'name': 'Cảnh báo hệ thống', 'severity': 'WARNING', 'repair_instruction': 'Kiểm tra chi tiết cảnh báo'},
    448: {'id_sungrow': 448, 'id_unified': 1101, 'name': 'Đấu ngược PV 3', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra cực tính và dây nối PV 3'},
    449: {'id_sungrow': 449, 'id_unified': 1101, 'name': 'Đấu ngược PV 4', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra cực tính và dây nối PV 4'},
    450: {'id_sungrow': 450, 'id_unified': 1101, 'name': 'Đấu ngược PV 5', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra cực tính và dây nối PV 5'},
    451: {'id_sungrow': 451, 'id_unified': 1101, 'name': 'Đấu ngược PV 6', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra cực tính và dây nối PV 6'},
    452: {'id_sungrow': 452, 'id_unified': 1101, 'name': 'Đấu ngược PV 7', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra cực tính và dây nối PV 7'},
    453: {'id_sungrow': 453, 'id_unified': 1101, 'name': 'Đấu ngược PV 8', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra cực tính và dây nối PV 8'},
    454: {'id_sungrow': 454, 'id_unified': 1101, 'name': 'Đấu ngược PV 9', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra cực tính và dây nối PV 9'},
    455: {'id_sungrow': 455, 'id_unified': 1101, 'name': 'Đấu ngược PV 10', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra cực tính và dây nối PV 10'},
    456: {'id_sungrow': 456, 'id_unified': 1101, 'name': 'Đấu ngược PV 11', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra cực tính và dây nối PV 11'},
    457: {'id_sungrow': 457, 'id_unified': 1101, 'name': 'Đấu ngược PV 12', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra cực tính và dây nối PV 12'},
    458: {'id_sungrow': 458, 'id_unified': 1101, 'name': 'Đấu ngược PV 13', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra cực tính và dây nối PV 13'},
    459: {'id_sungrow': 459, 'id_unified': 1101, 'name': 'Đấu ngược PV 14', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra cực tính và dây nối PV 14'},
    460: {'id_sungrow': 460, 'id_unified': 1101, 'name': 'Đấu ngược PV 15', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra cực tính và dây nối PV 15'},
    461: {'id_sungrow': 461, 'id_unified': 1101, 'name': 'Đấu ngược PV 16', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra cực tính và dây nối PV 16'},
    462: {'id_sungrow': 462, 'id_unified': 1101, 'name': 'Đấu ngược PV 17', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra cực tính và dây nối PV 17'},
    463: {'id_sungrow': 463, 'id_unified': 1101, 'name': 'Đấu ngược PV 18', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra cực tính và dây nối PV 18'},
    464: {'id_sungrow': 464, 'id_unified': 1101, 'name': 'Đấu ngược PV 19', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra cực tính và dây nối PV 19'},
    465: {'id_sungrow': 465, 'id_unified': 1101, 'name': 'Đấu ngược PV 20', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra cực tính và dây nối PV 20'},
    466: {'id_sungrow': 466, 'id_unified': 1101, 'name': 'Đấu ngược PV 21', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra cực tính và dây nối PV 21'},
    467: {'id_sungrow': 467, 'id_unified': 1101, 'name': 'Đấu ngược PV 22', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra cực tính và dây nối PV 22'},
    468: {'id_sungrow': 468, 'id_unified': 1101, 'name': 'Đấu ngược PV 23', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra cực tính và dây nối PV 23'},
    469: {'id_sungrow': 469, 'id_unified': 1101, 'name': 'Đấu ngược PV 24', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra cực tính và dây nối PV 24'},
    470: {'id_sungrow': 470, 'id_unified': 1101, 'name': 'Đấu ngược PV 25', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra cực tính và dây nối PV 25'},
    471: {'id_sungrow': 471, 'id_unified': 1101, 'name': 'Đấu ngược PV 26', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra cực tính và dây nối PV 26'},
    472: {'id_sungrow': 472, 'id_unified': 1101, 'name': 'Đấu ngược PV 27', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra cực tính và dây nối PV 27'},
    473: {'id_sungrow': 473, 'id_unified': 1101, 'name': 'Đấu ngược PV 28', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra cực tính và dây nối PV 28'},
    474: {'id_sungrow': 474, 'id_unified': 1101, 'name': 'Đấu ngược PV 29', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra cực tính và dây nối PV 29'},
    475: {'id_sungrow': 475, 'id_unified': 1101, 'name': 'Đấu ngược PV 30', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra cực tính và dây nối PV 30'},
    476: {'id_sungrow': 476, 'id_unified': 1101, 'name': 'Đấu ngược PV 31', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra cực tính và dây nối PV 31'},
    478: {'id_sungrow': 478, 'id_unified': 1101, 'name': 'Đấu ngược PV 32', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra cực tính và dây nối PV 32'},
    479: {'id_sungrow': 479, 'id_unified': 1101, 'name': 'Đấu ngược PV 33', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra cực tính và dây nối PV 33'},
    500: {'id_sungrow': 500, 'id_unified': 1703, 'name': 'Cảnh báo hệ thống', 'severity': 'WARNING', 'repair_instruction': 'Kiểm tra chi tiết cảnh báo'},
    501: {'id_sungrow': 501, 'id_unified': 1703, 'name': 'Cảnh báo hệ thống', 'severity': 'WARNING', 'repair_instruction': 'Kiểm tra chi tiết cảnh báo'},
    502: {'id_sungrow': 502, 'id_unified': 1703, 'name': 'Cảnh báo hệ thống', 'severity': 'WARNING', 'repair_instruction': 'Kiểm tra chi tiết cảnh báo'},
    503: {'id_sungrow': 503, 'id_unified': 1703, 'name': 'Cảnh báo hệ thống', 'severity': 'WARNING', 'repair_instruction': 'Kiểm tra chi tiết cảnh báo'},
    504: {'id_sungrow': 504, 'id_unified': 1703, 'name': 'Cảnh báo hệ thống', 'severity': 'WARNING', 'repair_instruction': 'Kiểm tra chi tiết cảnh báo'},
    505: {'id_sungrow': 505, 'id_unified': 1703, 'name': 'Cảnh báo hệ thống', 'severity': 'WARNING', 'repair_instruction': 'Kiểm tra chi tiết cảnh báo'},
    506: {'id_sungrow': 506, 'id_unified': 1703, 'name': 'Cảnh báo hệ thống', 'severity': 'WARNING', 'repair_instruction': 'Kiểm tra chi tiết cảnh báo'},
    507: {'id_sungrow': 507, 'id_unified': 1703, 'name': 'Cảnh báo hệ thống', 'severity': 'WARNING', 'repair_instruction': 'Kiểm tra chi tiết cảnh báo'},
    508: {'id_sungrow': 508, 'id_unified': 1703, 'name': 'Cảnh báo hệ thống', 'severity': 'WARNING', 'repair_instruction': 'Kiểm tra chi tiết cảnh báo'},
    509: {'id_sungrow': 509, 'id_unified': 1703, 'name': 'Cảnh báo hệ thống', 'severity': 'WARNING', 'repair_instruction': 'Kiểm tra chi tiết cảnh báo'},
    510: {'id_sungrow': 510, 'id_unified': 1703, 'name': 'Cảnh báo hệ thống', 'severity': 'WARNING', 'repair_instruction': 'Kiểm tra chi tiết cảnh báo'},
    511: {'id_sungrow': 511, 'id_unified': 1703, 'name': 'Cảnh báo hệ thống', 'severity': 'WARNING', 'repair_instruction': 'Kiểm tra chi tiết cảnh báo'},
    512: {'id_sungrow': 512, 'id_unified': 1703, 'name': 'Cảnh báo hệ thống', 'severity': 'WARNING', 'repair_instruction': 'Kiểm tra chi tiết cảnh báo'},
    513: {'id_sungrow': 513, 'id_unified': 1703, 'name': 'Cảnh báo hệ thống', 'severity': 'WARNING', 'repair_instruction': 'Kiểm tra chi tiết cảnh báo'},
    514: {'id_sungrow': 514, 'id_unified': 1703, 'name': 'Cảnh báo hệ thống', 'severity': 'WARNING', 'repair_instruction': 'Kiểm tra chi tiết cảnh báo'},
    515: {'id_sungrow': 515, 'id_unified': 1703, 'name': 'Cảnh báo hệ thống', 'severity': 'WARNING', 'repair_instruction': 'Kiểm tra chi tiết cảnh báo'},
    516: {'id_sungrow': 516, 'id_unified': 1703, 'name': 'Cảnh báo hệ thống', 'severity': 'WARNING', 'repair_instruction': 'Kiểm tra chi tiết cảnh báo'},
    517: {'id_sungrow': 517, 'id_unified': 1703, 'name': 'Cảnh báo hệ thống', 'severity': 'WARNING', 'repair_instruction': 'Kiểm tra chi tiết cảnh báo'},
    518: {'id_sungrow': 518, 'id_unified': 1703, 'name': 'Cảnh báo hệ thống', 'severity': 'WARNING', 'repair_instruction': 'Kiểm tra chi tiết cảnh báo'},
    532: {'id_sungrow': 532, 'id_unified': 1101, 'name': 'Ngược cực PV 1', 'severity': 'WARNING', 'repair_instruction': 'Kiểm tra cực tính và dây nối PV 1'},
    533: {'id_sungrow': 533, 'id_unified': 1101, 'name': 'Ngược cực PV 2', 'severity': 'WARNING', 'repair_instruction': 'Kiểm tra cực tính và dây nối PV 2'},
    534: {'id_sungrow': 534, 'id_unified': 1101, 'name': 'Ngược cực PV 3', 'severity': 'WARNING', 'repair_instruction': 'Kiểm tra cực tính và dây nối PV 3'},
    535: {'id_sungrow': 535, 'id_unified': 1101, 'name': 'Ngược cực PV 4', 'severity': 'WARNING', 'repair_instruction': 'Kiểm tra cực tính và dây nối PV 4'},
    536: {'id_sungrow': 536, 'id_unified': 1101, 'name': 'Ngược cực PV 5', 'severity': 'WARNING', 'repair_instruction': 'Kiểm tra cực tính và dây nối PV 5'},
    537: {'id_sungrow': 537, 'id_unified': 1101, 'name': 'Ngược cực PV 6', 'severity': 'WARNING', 'repair_instruction': 'Kiểm tra cực tính và dây nối PV 6'},
    538: {'id_sungrow': 538, 'id_unified': 1101, 'name': 'Ngược cực PV 7', 'severity': 'WARNING', 'repair_instruction': 'Kiểm tra cực tính và dây nối PV 7'},
    539: {'id_sungrow': 539, 'id_unified': 1101, 'name': 'Ngược cực PV 8', 'severity': 'WARNING', 'repair_instruction': 'Kiểm tra cực tính và dây nối PV 8'},
    540: {'id_sungrow': 540, 'id_unified': 1101, 'name': 'Ngược cực PV 9', 'severity': 'WARNING', 'repair_instruction': 'Kiểm tra cực tính và dây nối PV 9'},
    541: {'id_sungrow': 541, 'id_unified': 1101, 'name': 'Ngược cực PV 10', 'severity': 'WARNING', 'repair_instruction': 'Kiểm tra cực tính và dây nối PV 10'},
    542: {'id_sungrow': 542, 'id_unified': 1101, 'name': 'Ngược cực PV 11', 'severity': 'WARNING', 'repair_instruction': 'Kiểm tra cực tính và dây nối PV 11'},
    543: {'id_sungrow': 543, 'id_unified': 1101, 'name': 'Ngược cực PV 12', 'severity': 'WARNING', 'repair_instruction': 'Kiểm tra cực tính và dây nối PV 12'},
    544: {'id_sungrow': 544, 'id_unified': 1101, 'name': 'Ngược cực PV 13', 'severity': 'WARNING', 'repair_instruction': 'Kiểm tra cực tính và dây nối PV 13'},
    545: {'id_sungrow': 545, 'id_unified': 1101, 'name': 'Ngược cực PV 14', 'severity': 'WARNING', 'repair_instruction': 'Kiểm tra cực tính và dây nối PV 14'},
    546: {'id_sungrow': 546, 'id_unified': 1101, 'name': 'Ngược cực PV 15', 'severity': 'WARNING', 'repair_instruction': 'Kiểm tra cực tính và dây nối PV 15'},
    547: {'id_sungrow': 547, 'id_unified': 1101, 'name': 'Ngược cực PV 16', 'severity': 'WARNING', 'repair_instruction': 'Kiểm tra cực tính và dây nối PV 16'},
    548: {'id_sungrow': 548, 'id_unified': 1104, 'name': 'Đầu vào PV 1 bất thường', 'severity': 'WARNING', 'repair_instruction': 'Kiểm tra dây PV và đầu vào MPPT 1'},
    549: {'id_sungrow': 549, 'id_unified': 1104, 'name': 'Đầu vào PV 2 bất thường', 'severity': 'WARNING', 'repair_instruction': 'Kiểm tra dây PV và đầu vào MPPT 1'},
    550: {'id_sungrow': 550, 'id_unified': 1104, 'name': 'Đầu vào PV 3 bất thường', 'severity': 'WARNING', 'repair_instruction': 'Kiểm tra dây PV và đầu vào MPPT 2'},
    551: {'id_sungrow': 551, 'id_unified': 1104, 'name': 'Đầu vào PV 4 bất thường', 'severity': 'WARNING', 'repair_instruction': 'Kiểm tra dây PV và đầu vào MPPT 2'},
    552: {'id_sungrow': 552, 'id_unified': 1104, 'name': 'Đầu vào PV 5 bất thường', 'severity': 'WARNING', 'repair_instruction': 'Kiểm tra dây PV và đầu vào MPPT 3'},
    553: {'id_sungrow': 553, 'id_unified': 1104, 'name': 'Đầu vào PV 6 bất thường', 'severity': 'WARNING', 'repair_instruction': 'Kiểm tra dây PV và đầu vào MPPT 3'},
    554: {'id_sungrow': 554, 'id_unified': 1104, 'name': 'Đầu vào PV 7 bất thường', 'severity': 'WARNING', 'repair_instruction': 'Kiểm tra dây PV và đầu vào MPPT 4'},
    555: {'id_sungrow': 555, 'id_unified': 1104, 'name': 'Đầu vào PV 8 bất thường', 'severity': 'WARNING', 'repair_instruction': 'Kiểm tra dây PV và đầu vào MPPT 4'},
    556: {'id_sungrow': 556, 'id_unified': 1104, 'name': 'Đầu vào PV 9 bất thường', 'severity': 'WARNING', 'repair_instruction': 'Kiểm tra dây PV và đầu vào MPPT 5'},
    557: {'id_sungrow': 557, 'id_unified': 1104, 'name': 'Đầu vào PV 10 bất thường', 'severity': 'WARNING', 'repair_instruction': 'Kiểm tra dây PV và đầu vào MPPT 5'},
    558: {'id_sungrow': 558, 'id_unified': 1104, 'name': 'Đầu vào PV 11 bất thường', 'severity': 'WARNING', 'repair_instruction': 'Kiểm tra dây PV và đầu vào MPPT 6'},
    559: {'id_sungrow': 559, 'id_unified': 1104, 'name': 'Đầu vào PV 12 bất thường', 'severity': 'WARNING', 'repair_instruction': 'Kiểm tra dây PV và đầu vào MPPT 6'},
    560: {'id_sungrow': 560, 'id_unified': 1104, 'name': 'Đầu vào PV 13 bất thường', 'severity': 'WARNING', 'repair_instruction': 'Kiểm tra dây PV và đầu vào MPPT 7'},
    561: {'id_sungrow': 561, 'id_unified': 1104, 'name': 'Đầu vào PV 14 bất thường', 'severity': 'WARNING', 'repair_instruction': 'Kiểm tra dây PV và đầu vào MPPT 7'},
    562: {'id_sungrow': 562, 'id_unified': 1104, 'name': 'Đầu vào PV 15 bất thường', 'severity': 'WARNING', 'repair_instruction': 'Kiểm tra dây PV và đầu vào MPPT 8'},
    563: {'id_sungrow': 563, 'id_unified': 1104, 'name': 'Đầu vào PV 16 bất thường', 'severity': 'WARNING', 'repair_instruction': 'Kiểm tra dây PV và đầu vào MPPT 8'},
    564: {'id_sungrow': 564, 'id_unified': 1101, 'name': 'Ngược cực PV 17', 'severity': 'WARNING', 'repair_instruction': 'Kiểm tra cực tính và dây nối PV 17'},
    565: {'id_sungrow': 565, 'id_unified': 1101, 'name': 'Ngược cực PV 18', 'severity': 'WARNING', 'repair_instruction': 'Kiểm tra cực tính và dây nối PV 18'},
    566: {'id_sungrow': 566, 'id_unified': 1101, 'name': 'Ngược cực PV 19', 'severity': 'WARNING', 'repair_instruction': 'Kiểm tra cực tính và dây nối PV 19'},
    567: {'id_sungrow': 567, 'id_unified': 1101, 'name': 'Ngược cực PV 20', 'severity': 'WARNING', 'repair_instruction': 'Kiểm tra cực tính và dây nối PV 20'},
    568: {'id_sungrow': 568, 'id_unified': 1101, 'name': 'Ngược cực PV 21', 'severity': 'WARNING', 'repair_instruction': 'Kiểm tra cực tính và dây nối PV 21'},
    569: {'id_sungrow': 569, 'id_unified': 1101, 'name': 'Ngược cực PV 22', 'severity': 'WARNING', 'repair_instruction': 'Kiểm tra cực tính và dây nối PV 22'},
    570: {'id_sungrow': 570, 'id_unified': 1101, 'name': 'Ngược cực PV 23', 'severity': 'WARNING', 'repair_instruction': 'Kiểm tra cực tính và dây nối PV 23'},
    571: {'id_sungrow': 571, 'id_unified': 1101, 'name': 'Ngược cực PV 24', 'severity': 'WARNING', 'repair_instruction': 'Kiểm tra cực tính và dây nối PV 24'},
    572: {'id_sungrow': 572, 'id_unified': 1101, 'name': 'Ngược cực PV 25', 'severity': 'WARNING', 'repair_instruction': 'Kiểm tra cực tính và dây nối PV 25'},
    573: {'id_sungrow': 573, 'id_unified': 1101, 'name': 'Ngược cực PV 26', 'severity': 'WARNING', 'repair_instruction': 'Kiểm tra cực tính và dây nối PV 26'},
    574: {'id_sungrow': 574, 'id_unified': 1101, 'name': 'Ngược cực PV 27', 'severity': 'WARNING', 'repair_instruction': 'Kiểm tra cực tính và dây nối PV 27'},
    575: {'id_sungrow': 575, 'id_unified': 1101, 'name': 'Ngược cực PV 28', 'severity': 'WARNING', 'repair_instruction': 'Kiểm tra cực tính và dây nối PV 28'},
    576: {'id_sungrow': 576, 'id_unified': 1101, 'name': 'Ngược cực PV 29', 'severity': 'WARNING', 'repair_instruction': 'Kiểm tra cực tính và dây nối PV 29'},
    577: {'id_sungrow': 577, 'id_unified': 1101, 'name': 'Ngược cực PV 30', 'severity': 'WARNING', 'repair_instruction': 'Kiểm tra cực tính và dây nối PV 30'},
    578: {'id_sungrow': 578, 'id_unified': 1101, 'name': 'Ngược cực PV 31', 'severity': 'WARNING', 'repair_instruction': 'Kiểm tra cực tính và dây nối PV 31'},
    579: {'id_sungrow': 579, 'id_unified': 1101, 'name': 'Ngược cực PV 32', 'severity': 'WARNING', 'repair_instruction': 'Kiểm tra cực tính và dây nối PV 32'},
    580: {'id_sungrow': 580, 'id_unified': 1104, 'name': 'Đầu vào PV 17 bất thường', 'severity': 'WARNING', 'repair_instruction': 'Kiểm tra dây PV và đầu vào MPPT 9'},
    581: {'id_sungrow': 581, 'id_unified': 1104, 'name': 'Đầu vào PV 18 bất thường', 'severity': 'WARNING', 'repair_instruction': 'Kiểm tra dây PV và đầu vào MPPT 9'},
    582: {'id_sungrow': 582, 'id_unified': 1104, 'name': 'Đầu vào PV 19 bất thường', 'severity': 'WARNING', 'repair_instruction': 'Kiểm tra dây PV và đầu vào MPPT 10'},
    583: {'id_sungrow': 583, 'id_unified': 1104, 'name': 'Đầu vào PV 20 bất thường', 'severity': 'WARNING', 'repair_instruction': 'Kiểm tra dây PV và đầu vào MPPT 10'},
    584: {'id_sungrow': 584, 'id_unified': 1104, 'name': 'Đầu vào PV 21 bất thường', 'severity': 'WARNING', 'repair_instruction': 'Kiểm tra dây PV và đầu vào MPPT 11'},
    585: {'id_sungrow': 585, 'id_unified': 1104, 'name': 'Đầu vào PV 22 bất thường', 'severity': 'WARNING', 'repair_instruction': 'Kiểm tra dây PV và đầu vào MPPT 11'},
    586: {'id_sungrow': 586, 'id_unified': 1104, 'name': 'Đầu vào PV 23 bất thường', 'severity': 'WARNING', 'repair_instruction': 'Kiểm tra dây PV và đầu vào MPPT 12'},
    587: {'id_sungrow': 587, 'id_unified': 1104, 'name': 'Đầu vào PV 24 bất thường', 'severity': 'WARNING', 'repair_instruction': 'Kiểm tra dây PV và đầu vào MPPT 12'},
    588: {'id_sungrow': 588, 'id_unified': 1104, 'name': 'Đầu vào PV 25 bất thường', 'severity': 'WARNING', 'repair_instruction': 'Kiểm tra dây PV và đầu vào MPPT 13'},
    589: {'id_sungrow': 589, 'id_unified': 1104, 'name': 'Đầu vào PV 26 bất thường', 'severity': 'WARNING', 'repair_instruction': 'Kiểm tra dây PV và đầu vào MPPT 13'},
    590: {'id_sungrow': 590, 'id_unified': 1104, 'name': 'Đầu vào PV 27 bất thường', 'severity': 'WARNING', 'repair_instruction': 'Kiểm tra dây PV và đầu vào MPPT 14'},
    591: {'id_sungrow': 591, 'id_unified': 1104, 'name': 'Đầu vào PV 28 bất thường', 'severity': 'WARNING', 'repair_instruction': 'Kiểm tra dây PV và đầu vào MPPT 14'},
    592: {'id_sungrow': 592, 'id_unified': 1104, 'name': 'Đầu vào PV 29 bất thường', 'severity': 'WARNING', 'repair_instruction': 'Kiểm tra dây PV và đầu vào MPPT 15'},
    593: {'id_sungrow': 593, 'id_unified': 1104, 'name': 'Đầu vào PV 30 bất thường', 'severity': 'WARNING', 'repair_instruction': 'Kiểm tra dây PV và đầu vào MPPT 15'},
    594: {'id_sungrow': 594, 'id_unified': 1104, 'name': 'Đầu vào PV 31 bất thường', 'severity': 'WARNING', 'repair_instruction': 'Kiểm tra dây PV và đầu vào MPPT 16'},
    595: {'id_sungrow': 595, 'id_unified': 1104, 'name': 'Đầu vào PV 32 bất thường', 'severity': 'WARNING', 'repair_instruction': 'Kiểm tra dây PV và đầu vào MPPT 16'},
    600: {'id_sungrow': 600, 'id_unified': 1702, 'name': 'Lỗi hệ thống', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra hệ thống nội bộ biến tần, liên hệ nhà sản xuất'},
    601: {'id_sungrow': 601, 'id_unified': 1702, 'name': 'Lỗi hệ thống', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra hệ thống nội bộ biến tần, liên hệ nhà sản xuất'},
    602: {'id_sungrow': 602, 'id_unified': 1702, 'name': 'Lỗi hệ thống', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra hệ thống nội bộ biến tần, liên hệ nhà sản xuất'},
    603: {'id_sungrow': 603, 'id_unified': 1702, 'name': 'Lỗi hệ thống', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra hệ thống nội bộ biến tần, liên hệ nhà sản xuất'},
    604: {'id_sungrow': 604, 'id_unified': 1702, 'name': 'Lỗi hệ thống', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra hệ thống nội bộ biến tần, liên hệ nhà sản xuất'},
    605: {'id_sungrow': 605, 'id_unified': 1702, 'name': 'Lỗi hệ thống', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra hệ thống nội bộ biến tần, liên hệ nhà sản xuất'},
    606: {'id_sungrow': 606, 'id_unified': 1702, 'name': 'Lỗi hệ thống', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra hệ thống nội bộ biến tần, liên hệ nhà sản xuất'},
    607: {'id_sungrow': 607, 'id_unified': 1702, 'name': 'Lỗi hệ thống', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra hệ thống nội bộ biến tần, liên hệ nhà sản xuất'},
    608: {'id_sungrow': 608, 'id_unified': 1702, 'name': 'Lỗi hệ thống', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra hệ thống nội bộ biến tần, liên hệ nhà sản xuất'},
    609: {'id_sungrow': 609, 'id_unified': 1702, 'name': 'Lỗi hệ thống', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra hệ thống nội bộ biến tần, liên hệ nhà sản xuất'},
    610: {'id_sungrow': 610, 'id_unified': 1702, 'name': 'Lỗi hệ thống', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra hệ thống nội bộ biến tần, liên hệ nhà sản xuất'},
    611: {'id_sungrow': 611, 'id_unified': 1702, 'name': 'Lỗi hệ thống', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra hệ thống nội bộ biến tần, liên hệ nhà sản xuất'},
    612: {'id_sungrow': 612, 'id_unified': 1702, 'name': 'Lỗi hệ thống', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra hệ thống nội bộ biến tần, liên hệ nhà sản xuất'},
    613: {'id_sungrow': 613, 'id_unified': 1702, 'name': 'Lỗi hệ thống', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra hệ thống nội bộ biến tần, liên hệ nhà sản xuất'},
    614: {'id_sungrow': 614, 'id_unified': 1702, 'name': 'Lỗi hệ thống', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra hệ thống nội bộ biến tần, liên hệ nhà sản xuất'},
    615: {'id_sungrow': 615, 'id_unified': 1702, 'name': 'Lỗi hệ thống', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra hệ thống nội bộ biến tần, liên hệ nhà sản xuất'},
    616: {'id_sungrow': 616, 'id_unified': 1702, 'name': 'Lỗi hệ thống', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra hệ thống nội bộ biến tần, liên hệ nhà sản xuất'},
    617: {'id_sungrow': 617, 'id_unified': 1702, 'name': 'Lỗi hệ thống', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra hệ thống nội bộ biến tần, liên hệ nhà sản xuất'},
    618: {'id_sungrow': 618, 'id_unified': 1702, 'name': 'Lỗi hệ thống', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra hệ thống nội bộ biến tần, liên hệ nhà sản xuất'},
    619: {'id_sungrow': 619, 'id_unified': 1702, 'name': 'Lỗi hệ thống', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra hệ thống nội bộ biến tần, liên hệ nhà sản xuất'},
    620: {'id_sungrow': 620, 'id_unified': 1702, 'name': 'Lỗi hệ thống', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra hệ thống nội bộ biến tần, liên hệ nhà sản xuất'},
    621: {'id_sungrow': 621, 'id_unified': 1702, 'name': 'Lỗi hệ thống', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra hệ thống nội bộ biến tần, liên hệ nhà sản xuất'},
    622: {'id_sungrow': 622, 'id_unified': 1702, 'name': 'Lỗi hệ thống', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra hệ thống nội bộ biến tần, liên hệ nhà sản xuất'},
    623: {'id_sungrow': 623, 'id_unified': 1702, 'name': 'Lỗi hệ thống', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra hệ thống nội bộ biến tần, liên hệ nhà sản xuất'},
    624: {'id_sungrow': 624, 'id_unified': 1702, 'name': 'Lỗi hệ thống', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra hệ thống nội bộ biến tần, liên hệ nhà sản xuất'},
    635: {'id_sungrow': 635, 'id_unified': 1703, 'name': 'Cảnh báo hệ thống', 'severity': 'WARNING', 'repair_instruction': 'Kiểm tra chi tiết cảnh báo'},
    636: {'id_sungrow': 636, 'id_unified': 1703, 'name': 'Cảnh báo hệ thống', 'severity': 'WARNING', 'repair_instruction': 'Kiểm tra chi tiết cảnh báo'},
    637: {'id_sungrow': 637, 'id_unified': 1703, 'name': 'Cảnh báo hệ thống', 'severity': 'WARNING', 'repair_instruction': 'Kiểm tra chi tiết cảnh báo'},
    638: {'id_sungrow': 638, 'id_unified': 1703, 'name': 'Cảnh báo hệ thống', 'severity': 'WARNING', 'repair_instruction': 'Kiểm tra chi tiết cảnh báo'},
    800: {'id_sungrow': 800, 'id_unified': 1702, 'name': 'Lỗi hệ thống', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra hệ thống nội bộ biến tần, liên hệ nhà sản xuất'},
    801: {'id_sungrow': 801, 'id_unified': 1702, 'name': 'Lỗi hệ thống', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra hệ thống nội bộ biến tần, liên hệ nhà sản xuất'},
    802: {'id_sungrow': 802, 'id_unified': 1702, 'name': 'Lỗi hệ thống', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra hệ thống nội bộ biến tần, liên hệ nhà sản xuất'},
    803: {'id_sungrow': 803, 'id_unified': 1702, 'name': 'Lỗi hệ thống', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra hệ thống nội bộ biến tần, liên hệ nhà sản xuất'},
    804: {'id_sungrow': 804, 'id_unified': 1702, 'name': 'Lỗi hệ thống', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra hệ thống nội bộ biến tần, liên hệ nhà sản xuất'},
    805: {'id_sungrow': 805, 'id_unified': 1702, 'name': 'Lỗi hệ thống', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra hệ thống nội bộ biến tần, liên hệ nhà sản xuất'},
    806: {'id_sungrow': 806, 'id_unified': 1702, 'name': 'Lỗi hệ thống', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra hệ thống nội bộ biến tần, liên hệ nhà sản xuất'},
    807: {'id_sungrow': 807, 'id_unified': 1702, 'name': 'Lỗi hệ thống', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra hệ thống nội bộ biến tần, liên hệ nhà sản xuất'},
    900: {'id_sungrow': 900, 'id_unified': 1703, 'name': 'Cảnh báo hệ thống', 'severity': 'WARNING', 'repair_instruction': 'Kiểm tra chi tiết cảnh báo'},
    901: {'id_sungrow': 901, 'id_unified': 1703, 'name': 'Cảnh báo hệ thống', 'severity': 'WARNING', 'repair_instruction': 'Kiểm tra chi tiết cảnh báo'},
    902: {'id_sungrow': 902, 'id_unified': 1703, 'name': 'Cảnh báo hệ thống', 'severity': 'WARNING', 'repair_instruction': 'Kiểm tra chi tiết cảnh báo'},
    903: {'id_sungrow': 903, 'id_unified': 1703, 'name': 'Cảnh báo hệ thống', 'severity': 'WARNING', 'repair_instruction': 'Kiểm tra chi tiết cảnh báo'},
    904: {'id_sungrow': 904, 'id_unified': 1703, 'name': 'Cảnh báo hệ thống', 'severity': 'WARNING', 'repair_instruction': 'Kiểm tra chi tiết cảnh báo'},
    905: {'id_sungrow': 905, 'id_unified': 1703, 'name': 'Cảnh báo hệ thống', 'severity': 'WARNING', 'repair_instruction': 'Kiểm tra chi tiết cảnh báo'},
    906: {'id_sungrow': 906, 'id_unified': 1703, 'name': 'Cảnh báo hệ thống', 'severity': 'WARNING', 'repair_instruction': 'Kiểm tra chi tiết cảnh báo'},
    907: {'id_sungrow': 907, 'id_unified': 1703, 'name': 'Cảnh báo hệ thống', 'severity': 'WARNING', 'repair_instruction': 'Kiểm tra chi tiết cảnh báo'},
    908: {'id_sungrow': 908, 'id_unified': 1703, 'name': 'Cảnh báo hệ thống', 'severity': 'WARNING', 'repair_instruction': 'Kiểm tra chi tiết cảnh báo'},
    909: {'id_sungrow': 909, 'id_unified': 1703, 'name': 'Cảnh báo hệ thống', 'severity': 'WARNING', 'repair_instruction': 'Kiểm tra chi tiết cảnh báo'},
    910: {'id_sungrow': 910, 'id_unified': 1703, 'name': 'Cảnh báo hệ thống', 'severity': 'WARNING', 'repair_instruction': 'Kiểm tra chi tiết cảnh báo'},
    911: {'id_sungrow': 911, 'id_unified': 1703, 'name': 'Cảnh báo hệ thống', 'severity': 'WARNING', 'repair_instruction': 'Kiểm tra chi tiết cảnh báo'},
    1096: {'id_sungrow': 1096, 'id_unified': 1702, 'name': 'Lỗi hệ thống', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra hệ thống nội bộ biến tần, liên hệ nhà sản xuất'},
    1097: {'id_sungrow': 1097, 'id_unified': 1702, 'name': 'Lỗi hệ thống', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra hệ thống nội bộ biến tần, liên hệ nhà sản xuất'},
    1098: {'id_sungrow': 1098, 'id_unified': 1702, 'name': 'Lỗi hệ thống', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra hệ thống nội bộ biến tần, liên hệ nhà sản xuất'},
    1099: {'id_sungrow': 1099, 'id_unified': 1702, 'name': 'Lỗi hệ thống', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra hệ thống nội bộ biến tần, liên hệ nhà sản xuất'},
    1100: {'id_sungrow': 1100, 'id_unified': 1702, 'name': 'Lỗi hệ thống', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra hệ thống nội bộ biến tần, liên hệ nhà sản xuất'},
    1101: {'id_sungrow': 1101, 'id_unified': 1702, 'name': 'Lỗi hệ thống', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra hệ thống nội bộ biến tần, liên hệ nhà sản xuất'},
    1102: {'id_sungrow': 1102, 'id_unified': 1702, 'name': 'Lỗi hệ thống', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra hệ thống nội bộ biến tần, liên hệ nhà sản xuất'},
    1103: {'id_sungrow': 1103, 'id_unified': 1702, 'name': 'Lỗi hệ thống', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra hệ thống nội bộ biến tần, liên hệ nhà sản xuất'},
    1104: {'id_sungrow': 1104, 'id_unified': 1702, 'name': 'Lỗi hệ thống', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra hệ thống nội bộ biến tần, liên hệ nhà sản xuất'},
    1105: {'id_sungrow': 1105, 'id_unified': 1702, 'name': 'Lỗi hệ thống', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra hệ thống nội bộ biến tần, liên hệ nhà sản xuất'},
    1106: {'id_sungrow': 1106, 'id_unified': 1702, 'name': 'Lỗi hệ thống', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra hệ thống nội bộ biến tần, liên hệ nhà sản xuất'},
    1107: {'id_sungrow': 1107, 'id_unified': 1702, 'name': 'Lỗi hệ thống', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra hệ thống nội bộ biến tần, liên hệ nhà sản xuất'},
    1108: {'id_sungrow': 1108, 'id_unified': 1702, 'name': 'Lỗi hệ thống', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra hệ thống nội bộ biến tần, liên hệ nhà sản xuất'},
    1109: {'id_sungrow': 1109, 'id_unified': 1702, 'name': 'Lỗi hệ thống', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra hệ thống nội bộ biến tần, liên hệ nhà sản xuất'},
    1110: {'id_sungrow': 1110, 'id_unified': 1702, 'name': 'Lỗi hệ thống', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra hệ thống nội bộ biến tần, liên hệ nhà sản xuất'},
    1111: {'id_sungrow': 1111, 'id_unified': 1702, 'name': 'Lỗi hệ thống', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra hệ thống nội bộ biến tần, liên hệ nhà sản xuất'},
    1112: {'id_sungrow': 1112, 'id_unified': 1702, 'name': 'Lỗi hệ thống', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra hệ thống nội bộ biến tần, liên hệ nhà sản xuất'},
    1113: {'id_sungrow': 1113, 'id_unified': 1702, 'name': 'Lỗi hệ thống', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra hệ thống nội bộ biến tần, liên hệ nhà sản xuất'},
    1114: {'id_sungrow': 1114, 'id_unified': 1702, 'name': 'Lỗi hệ thống', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra hệ thống nội bộ biến tần, liên hệ nhà sản xuất'},
    1115: {'id_sungrow': 1115, 'id_unified': 1702, 'name': 'Lỗi hệ thống', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra hệ thống nội bộ biến tần, liên hệ nhà sản xuất'},
    1116: {'id_sungrow': 1116, 'id_unified': 1702, 'name': 'Lỗi hệ thống', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra hệ thống nội bộ biến tần, liên hệ nhà sản xuất'},
    1117: {'id_sungrow': 1117, 'id_unified': 1702, 'name': 'Lỗi hệ thống', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra hệ thống nội bộ biến tần, liên hệ nhà sản xuất'},
    1118: {'id_sungrow': 1118, 'id_unified': 1702, 'name': 'Lỗi hệ thống', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra hệ thống nội bộ biến tần, liên hệ nhà sản xuất'},
    1119: {'id_sungrow': 1119, 'id_unified': 1702, 'name': 'Lỗi hệ thống', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra hệ thống nội bộ biến tần, liên hệ nhà sản xuất'},
    1120: {'id_sungrow': 1120, 'id_unified': 1702, 'name': 'Lỗi hệ thống', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra hệ thống nội bộ biến tần, liên hệ nhà sản xuất'},
    1121: {'id_sungrow': 1121, 'id_unified': 1702, 'name': 'Lỗi hệ thống', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra hệ thống nội bộ biến tần, liên hệ nhà sản xuất'},
    1122: {'id_sungrow': 1122, 'id_unified': 1702, 'name': 'Lỗi hệ thống', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra hệ thống nội bộ biến tần, liên hệ nhà sản xuất'},
    1548: {'id_sungrow': 1548, 'id_unified': 1111, 'name': 'Dòng trào ngược dây String 1', 'severity': 'WARNING', 'repair_instruction': 'Kiểm tra dòng ngược chiều trong dây'},
    1549: {'id_sungrow': 1549, 'id_unified': 1111, 'name': 'Dòng trào ngược dây String 2', 'severity': 'WARNING', 'repair_instruction': 'Kiểm tra dòng ngược chiều trong dây'},
    1550: {'id_sungrow': 1550, 'id_unified': 1111, 'name': 'Dòng trào ngược dây String 3', 'severity': 'WARNING', 'repair_instruction': 'Kiểm tra dòng ngược chiều trong dây'},
    1551: {'id_sungrow': 1551, 'id_unified': 1111, 'name': 'Dòng trào ngược dây String 4', 'severity': 'WARNING', 'repair_instruction': 'Kiểm tra dòng ngược chiều trong dây'},
    1552: {'id_sungrow': 1552, 'id_unified': 1111, 'name': 'Dòng trào ngược dây String 5', 'severity': 'WARNING', 'repair_instruction': 'Kiểm tra dòng ngược chiều trong dây'},
    1553: {'id_sungrow': 1553, 'id_unified': 1111, 'name': 'Dòng trào ngược dây String 6', 'severity': 'WARNING', 'repair_instruction': 'Kiểm tra dòng ngược chiều trong dây'},
    1554: {'id_sungrow': 1554, 'id_unified': 1111, 'name': 'Dòng trào ngược dây String 7', 'severity': 'WARNING', 'repair_instruction': 'Kiểm tra dòng ngược chiều trong dây'},
    1555: {'id_sungrow': 1555, 'id_unified': 1111, 'name': 'Dòng trào ngược dây String 8', 'severity': 'WARNING', 'repair_instruction': 'Kiểm tra dòng ngược chiều trong dây'},
    1556: {'id_sungrow': 1556, 'id_unified': 1111, 'name': 'Dòng trào ngược dây String 9', 'severity': 'WARNING', 'repair_instruction': 'Kiểm tra dòng ngược chiều trong dây'},
    1557: {'id_sungrow': 1557, 'id_unified': 1111, 'name': 'Dòng trào ngược dây String 10', 'severity': 'WARNING', 'repair_instruction': 'Kiểm tra dòng ngược chiều trong dây'},
    1558: {'id_sungrow': 1558, 'id_unified': 1111, 'name': 'Dòng trào ngược dây String 11', 'severity': 'WARNING', 'repair_instruction': 'Kiểm tra dòng ngược chiều trong dây'},
    1560: {'id_sungrow': 1560, 'id_unified': 1111, 'name': 'Dòng trào ngược dây String 12', 'severity': 'WARNING', 'repair_instruction': 'Kiểm tra dòng ngược chiều trong dây'},
    1561: {'id_sungrow': 1561, 'id_unified': 1111, 'name': 'Dòng trào ngược dây String 13', 'severity': 'WARNING', 'repair_instruction': 'Kiểm tra dòng ngược chiều trong dây'},
    1562: {'id_sungrow': 1562, 'id_unified': 1111, 'name': 'Dòng trào ngược dây String 14', 'severity': 'WARNING', 'repair_instruction': 'Kiểm tra dòng ngược chiều trong dây'},
    1563: {'id_sungrow': 1563, 'id_unified': 1111, 'name': 'Dòng trào ngược dây String 15', 'severity': 'WARNING', 'repair_instruction': 'Kiểm tra dòng ngược chiều trong dây'},
    1564: {'id_sungrow': 1564, 'id_unified': 1111, 'name': 'Dòng trào ngược dây String 16', 'severity': 'WARNING', 'repair_instruction': 'Kiểm tra dòng ngược chiều trong dây'},
    1565: {'id_sungrow': 1565, 'id_unified': 1111, 'name': 'Dòng trào ngược dây String 17', 'severity': 'WARNING', 'repair_instruction': 'Kiểm tra dòng ngược chiều trong dây'},
    1566: {'id_sungrow': 1566, 'id_unified': 1111, 'name': 'Dòng trào ngược dây String 18', 'severity': 'WARNING', 'repair_instruction': 'Kiểm tra dòng ngược chiều trong dây'},
    1567: {'id_sungrow': 1567, 'id_unified': 1111, 'name': 'Dòng trào ngược dây String 19', 'severity': 'WARNING', 'repair_instruction': 'Kiểm tra dòng ngược chiều trong dây'},
    1568: {'id_sungrow': 1568, 'id_unified': 1111, 'name': 'Dòng trào ngược dây String 20', 'severity': 'WARNING', 'repair_instruction': 'Kiểm tra dòng ngược chiều trong dây'},
    1569: {'id_sungrow': 1569, 'id_unified': 1111, 'name': 'Dòng trào ngược dây String 21', 'severity': 'WARNING', 'repair_instruction': 'Kiểm tra dòng ngược chiều trong dây'},
    1570: {'id_sungrow': 1570, 'id_unified': 1111, 'name': 'Dòng trào ngược dây String 22', 'severity': 'WARNING', 'repair_instruction': 'Kiểm tra dòng ngược chiều trong dây'},
    1571: {'id_sungrow': 1571, 'id_unified': 1111, 'name': 'Dòng trào ngược dây String 23', 'severity': 'WARNING', 'repair_instruction': 'Kiểm tra dòng ngược chiều trong dây'},
    1572: {'id_sungrow': 1572, 'id_unified': 1111, 'name': 'Dòng trào ngược dây String 24', 'severity': 'WARNING', 'repair_instruction': 'Kiểm tra dòng ngược chiều trong dây'},
    1573: {'id_sungrow': 1573, 'id_unified': 1111, 'name': 'Dòng trào ngược dây String 25', 'severity': 'WARNING', 'repair_instruction': 'Kiểm tra dòng ngược chiều trong dây'},
    1574: {'id_sungrow': 1574, 'id_unified': 1111, 'name': 'Dòng trào ngược dây String 26', 'severity': 'WARNING', 'repair_instruction': 'Kiểm tra dòng ngược chiều trong dây'},
    1575: {'id_sungrow': 1575, 'id_unified': 1111, 'name': 'Dòng trào ngược dây String 27', 'severity': 'WARNING', 'repair_instruction': 'Kiểm tra dòng ngược chiều trong dây'},
    1576: {'id_sungrow': 1576, 'id_unified': 1111, 'name': 'Dòng trào ngược dây String 28', 'severity': 'WARNING', 'repair_instruction': 'Kiểm tra dòng ngược chiều trong dây'},
    1577: {'id_sungrow': 1577, 'id_unified': 1111, 'name': 'Dòng trào ngược dây String 29', 'severity': 'WARNING', 'repair_instruction': 'Kiểm tra dòng ngược chiều trong dây'},
    1578: {'id_sungrow': 1578, 'id_unified': 1111, 'name': 'Dòng trào ngược dây String 30', 'severity': 'WARNING', 'repair_instruction': 'Kiểm tra dòng ngược chiều trong dây'},
    1579: {'id_sungrow': 1579, 'id_unified': 1111, 'name': 'Dòng trào ngược dây String 31', 'severity': 'WARNING', 'repair_instruction': 'Kiểm tra dòng ngược chiều trong dây'},
    1616: {'id_sungrow': 1616, 'id_unified': 1409, 'name': 'Lỗi board điều khiển', 'severity': 'ERROR', 'repair_instruction': 'Kiểm tra phần cứng board điều khiển'},
}


HUAWEI_FAULT_MAP = {
    200: {"id_huawei": 200, "id_unified": 0, "name": "Vận hành bình thường", "severity": "STABLE", "repair_instruction": "Bình thường."},
    201: {"id_huawei": 201, "id_unified": 1001, "name": "Quá điện áp lưới", "severity": "ERROR", "repair_instruction": "Kiểm tra điện áp lưới."},
    202: {"id_huawei": 202, "id_unified": 1003, "name": "Thấp điện áp lưới", "severity": "ERROR", "repair_instruction": "Kiểm tra điện áp lưới."},
    203: {"id_huawei": 203, "id_unified": 1005, "name": "Quá tần số lưới", "severity": "ERROR", "repair_instruction": "Kiểm tra tần số."},
    204: {"id_huawei": 204, "id_unified": 1006, "name": "Thấp tần số lưới", "severity": "ERROR", "repair_instruction": "Kiểm tra tần số."},
    205: {"id_huawei": 205, "id_unified": 1007, "name": "Mất điện lưới", "severity": "ERROR", "repair_instruction": "Kiểm tra cầu dao AC."},
    206: {"id_huawei": 206, "id_unified": 1009, "name": "Lỗi pha lưới", "severity": "ERROR", "repair_instruction": "Kiểm tra thứ tự pha."},
    2011: {"id_huawei": 2011, "id_unified": 1102, "name": "Quá điện áp DC", "severity": "ERROR", "repair_instruction": "Kiểm tra điện áp PV."},
    2012: {"id_huawei": 2012, "id_unified": 1202, "name": "Lỗi cách điện DC", "severity": "ERROR", "repair_instruction": "Kiểm tra cách điện."},
    2013: {"id_huawei": 2013, "id_unified": 1206, "name": "Lỗi nối đất", "severity": "ERROR", "repair_instruction": "Kiểm tra tiếp đất."},
    2014: {"id_huawei": 2014, "id_unified": 1201, "name": "Dòng rò", "severity": "ERROR", "repair_instruction": "Kiểm tra dòng rò."},
    2015: {"id_huawei": 2015, "id_unified": 1105, "name": "Lỗi dây PV", "severity": "WARNING", "repair_instruction": "Kiểm tra dây nối."},
    2021: {"id_huawei": 2021, "id_unified": 1301, "name": "Quá nhiệt", "severity": "ERROR", "repair_instruction": "Kiểm tra thông gió."},
    2022: {"id_huawei": 2022, "id_unified": 1401, "name": "Lỗi quạt", "severity": "WARNING", "repair_instruction": "Kiểm tra quạt."},
}

# 
# Key = Decimal value of the official Huawei hex state code (e.g. 0x0200 = 512)
# Retrieved from Modbus register 32089 (uint16)
HUAWEI_STATE_MAP = {
    # Chờ và khởi động
    0:    {"id_huawei": 0,    "id_unified": 12, "name": "Chờ khởi tạo",              "severity": "STABLE",     "description": "Biến tần đã khởi tạo và đang chờ"},
    1:    {"id_huawei": 1,    "id_unified": 13, "name": "Dò lưới",                   "severity": "STABLE",     "description": "Đang dò thông số lưới"},
    2:    {"id_huawei": 2,    "id_unified": 14, "name": "Kiểm tra cách điện",        "severity": "STABLE",     "description": "Đang kiểm tra kháng trở cách điện"},
    3:    {"id_huawei": 3,    "id_unified": 15, "name": "Tự kiểm tra",               "severity": "STABLE",     "description": "Tự kiểm tra trước khi khởi động"},
    256:  {"id_huawei": 256,  "id_unified": 3,  "name": "Đang khởi động",            "severity": "STABLE",     "description": "Biến tần đang khởi động"},

    # Vận hành
    512:  {"id_huawei": 512,  "id_unified": 1,  "name": "Vận hành",                  "severity": "STABLE",     "description": "Biến tần hoạt động bình thường"},
    513:  {"id_huawei": 513,  "id_unified": 7,  "name": "Giảm công suất",            "severity": "WARNING",    "description": "Vận hành với công suất giảm"},
    514:  {"id_huawei": 514,  "id_unified": 20, "name": "Giới hạn công suất",        "severity": "WARNING",    "description": "Công suất kết nối lưới bị giới hạn"},
    515:  {"id_huawei": 515,  "id_unified": 16, "name": "Vận hành độc lập",          "severity": "WARNING",    "description": "Chế độ vận hành off-grid"},
    2560: {"id_huawei": 2560, "id_unified": 8,  "name": "Vận hành theo lệnh",        "severity": "WARNING",    "description": "Sạc off-grid / vận hành theo lệnh điều độ"},

    # Tắt
    768:  {"id_huawei": 768,  "id_unified": 5,  "name": "Lỗi",                       "severity": "ERROR",      "description": "Phát hiện lỗi"},
    769:  {"id_huawei": 769,  "id_unified": 19, "name": "Đang tắt",                  "severity": "WARNING",    "description": "Quá trình tắt đang diễn ra"},
    770:  {"id_huawei": 770,  "id_unified": 9,  "name": "Lỗi truyền thông",          "severity": "ERROR",      "description": "Mất kết nối truyền thông"},
    771:  {"id_huawei": 771,  "id_unified": 10, "name": "Dừng khẩn cấp",             "severity": "ERROR",      "description": "Kích hoạt dừng khẩn cấp"},
    772:  {"id_huawei": 772,  "id_unified": 20, "name": "Giới hạn công suất",        "severity": "WARNING",    "description": "Tắt do giới hạn công suất"},
    773:  {"id_huawei": 773,  "id_unified": 11, "name": "Dừng bằng nút",             "severity": "ERROR",      "description": "Dừng thủ công"},
    774:  {"id_huawei": 774,  "id_unified": 4,  "name": "Đã dừng",                   "severity": "ERROR",      "description": "Công tắc DC ngắt"},
    775:  {"id_huawei": 775,  "id_unified": 19, "name": "Đang tắt",                  "severity": "WARNING",    "description": "Cắt nhanh"},
    776:  {"id_huawei": 776,  "id_unified": 5,  "name": "Lỗi",                       "severity": "ERROR",      "description": "Công suất đầu vào quá thấp"},

    # Lập lịch lưới
    1025: {"id_huawei": 1025, "id_unified": 23, "name": "Lập lịch cosφ–P",           "severity": "STABLE",     "description": "Điều độ theo đường cong cosφ–P"},
    1026: {"id_huawei": 1026, "id_unified": 24, "name": "Lập lịch Q–U",              "severity": "STABLE",     "description": "Điều độ theo đường cong Q–U"},
    1027: {"id_huawei": 1027, "id_unified": 25, "name": "Lập lịch PF–U",             "severity": "STABLE",     "description": "Điều độ theo đường cong PF–U"},
    1028: {"id_huawei": 1028, "id_unified": 26, "name": "Lập lịch tiếp điểm khô",   "severity": "STABLE",     "description": "Điều độ qua tiếp điểm khô"},
    1029: {"id_huawei": 1029, "id_unified": 27, "name": "Lập lịch Q–P",              "severity": "STABLE",     "description": "Điều độ theo đường cong Q–P"},

    # Kiểm tra & chẩn đoán
    1280: {"id_huawei": 1280, "id_unified": 28, "name": "Sẵn sàng kiểm tra định kỳ", "severity": "STABLE",    "description": "Sẵn sàng kiểm tra định kỳ"},
    1281: {"id_huawei": 1281, "id_unified": 29, "name": "Đang kiểm tra định kỳ",     "severity": "WARNING",   "description": "Đang thực hiện kiểm tra định kỳ"},
    1536: {"id_huawei": 1536, "id_unified": 30, "name": "Đang kiểm tra",             "severity": "WARNING",   "description": "Kiểm tra đang diễn ra"},
    1792: {"id_huawei": 1792, "id_unified": 31, "name": "Tự kiểm AFCI",              "severity": "WARNING",   "description": "Tự kiểm bộ cắt hồ quang"},
    2048: {"id_huawei": 2048, "id_unified": 32, "name": "Quét I-V",                  "severity": "WARNING",   "description": "Đang quét đường cong I-V"},
    2304: {"id_huawei": 2304, "id_unified": 33, "name": "Dò đầu vào DC",             "severity": "WARNING",   "description": "Đang dò đầu vào DC"},

    # Chờ khác
    40960:{"id_huawei": 40960,"id_unified": 22, "name": "Ngủ",                       "severity": "DISCONNECT", "description": "Không có bức xạ, biến tần ngủ"}
}


SUNGROW_STATE_MAP = {
    0:      {'id_sungrow': 0,     'id_unified': 1,  'name': 'Vận hành',              'severity': 'STABLE',     'description': 'Biến tần hoạt động bình thường'},
    0x7d1:  {'id_sungrow': 2001,  'id_unified': 13, 'name': 'Dò lưới',               'severity': 'STABLE',     'description': 'Đang dò điều kiện lưới'},
    0x7d2:  {'id_sungrow': 2002,  'id_unified': 14, 'name': 'Kiểm tra cách điện',    'severity': 'STABLE',     'description': 'Đang kiểm tra kháng trở cách điện'},
    0x7d3:  {'id_sungrow': 2003,  'id_unified': 15, 'name': 'Tự kiểm tra',           'severity': 'STABLE',     'description': 'Đang tự kiểm tra nội bộ'},
    0x7d4:  {'id_sungrow': 2004,  'id_unified': 19, 'name': 'Đang tắt',              'severity': 'STABLE',     'description': 'Biến tần đang tắt'},
    0x7d5:  {'id_sungrow': 2005,  'id_unified': 20, 'name': 'Giới hạn công suất',    'severity': 'WARNING',    'description': 'Công suất đầu ra bị giới hạn'},
    0x7d6:  {'id_sungrow': 2006,  'id_unified': 21, 'name': 'Chờ phục hồi lưới',     'severity': 'WARNING',    'description': 'Đang chờ lưới phục hồi'},
    0x7d7:  {'id_sungrow': 2007,  'id_unified': 22, 'name': 'Ngủ',                   'severity': 'STABLE',     'description': 'Chế độ ngủ (ban đêm hoặc không có PV)'},
    0x7d8:  {'id_sungrow': 2008,  'id_unified': 17, 'name': 'Bảo trì',               'severity': 'STABLE',     'description': 'Chế độ bảo trì hoặc sửa chữa'},
    0x7d9:  {'id_sungrow': 2009,  'id_unified': 18, 'name': 'Đang nâng cấp',         'severity': 'STABLE',     'description': 'Đang nâng cấp firmware'},
    0x7da:  {'id_sungrow': 2010,  'id_unified': 16, 'name': 'Vận hành độc lập',      'severity': 'STABLE',     'description': 'Vận hành off-grid'},
    0x1111: {'id_sungrow': 4369,  'id_unified': 15, 'name': 'Tự kiểm',               'severity': 'STABLE',     'description': 'Tự kiểm hệ thống hoặc chưa khởi tạo'},
    0x1200: {'id_sungrow': 4608,  'id_unified': 12, 'name': 'Chờ khởi tạo',          'severity': 'STABLE',     'description': 'Chờ ban đầu sau khởi động'},
    0x1300: {'id_sungrow': 4864,  'id_unified': 11, 'name': 'Dừng bằng nút',         'severity': 'STABLE',     'description': 'Dừng thủ công qua LCD hoặc lệnh từ xa'},
    0x1400: {'id_sungrow': 5120,  'id_unified': 2,  'name': 'Chờ',                   'severity': 'DISCONNECT',     'description': 'Chờ do DC đầu vào không đủ'},
    0x1500: {'id_sungrow': 5376,  'id_unified': 10, 'name': 'Dừng khẩn cấp',         'severity': 'ERROR',      'description': 'Kích hoạt dừng khẩn cấp'},
    0x1600: {'id_sungrow': 5632,  'id_unified': 3,  'name': 'Đang khởi động',        'severity': 'STABLE',     'description': 'Đang khởi động và đồng bộ lưới'},
    0x2500: {'id_sungrow': 9472,  'id_unified': 9,  'name': 'Lỗi truyền thông',      'severity': 'DISCONNECT', 'description': 'Phát hiện lỗi truyền thông'},
    0x5500: {'id_sungrow': 21760, 'id_unified': 5,  'name': 'Lỗi',                   'severity': 'ERROR',      'description': 'Xảy ra lỗi, biến tần dừng'},
    0x8000: {'id_sungrow': 32768, 'id_unified': 4,  'name': 'Dừng',                  'severity': 'STABLE',     'description': 'Biến tần đã dừng'},
    0x8100: {'id_sungrow': 33024, 'id_unified': 7,  'name': 'Giảm công suất',        'severity': 'WARNING',    'description': 'Vận hành với công suất giảm'},
    0x8200: {'id_sungrow': 33280, 'id_unified': 8,  'name': 'Vận hành theo lệnh',    'severity': 'WARNING',     'description': 'Vận hành theo điều độ'},
    0x9100: {'id_sungrow': 37120, 'id_unified': 6,  'name': 'Vận hành có cảnh báo',  'severity': 'WARNING',    'description': 'Vận hành với cảnh báo đang hoạt động'},
}


class FaultStateService:
    def __init__(self):
        self.state_maps = {
            "HUAWEI": HUAWEI_STATE_MAP,
            "SUNGROW": SUNGROW_STATE_MAP
            }
        self.fault_maps = {
            "HUAWEI": HUAWEI_FAULT_MAP,
            "SUNGROW": SUNGROW_FAULT_MAP
            }


# ============================================================
# ALIASES — dùng cho fault_service.py
# ============================================================

# Dict theo brand: FAULT_MAPS["HUAWEI"] -> HUAWEI_FAULT_MAP
FAULT_MAPS = {
    "HUAWEI": HUAWEI_FAULT_MAP,
    "SUNGROW": SUNGROW_FAULT_MAP,
}

# Dict theo brand: STATE_MAPS["HUAWEI"] -> HUAWEI_STATE_MAP
STATE_MAPS = {
    "HUAWEI": HUAWEI_STATE_MAP,
    "SUNGROW": SUNGROW_STATE_MAP,
}

# Huawei Modbus: map raw status_code từ thanh ghi Modbus 
# sang id_unified (state code trong HUAWEI_STATE_MAP)
# Với Huawei SUN2000, thanh ghi 32089 trả về integer state trực tiếp
# (0=Standby, 1=Grid-connected, 2=Grid-connected normally, ...)
# map này convert về id Huawei state map (0-13)
HUAWEI_MODBUS_MAP = {
    0: 0,    # INITIAL_STANDBY
    1: 5,    # RUNNING
    2: 5,    # RUNNING (grid connected normally)
    3: 6,    # ALARM_RUNNING
    4: 7,    # DERATING
    5: 8,    # STOPPED
    6: 9,    # FAULT
    7: 10,   # UPGRADING
    8: 11,   # SHUTTING_DOWN
    9: 1,    # GRID_DETECTING
    10: 2,   # INSULATION_CHECK
    11: 3,   # SELF_CHECK
    12: 4,   # STARTING
    13: 12,  # GRID_FAULT_WAIT
    14: 13,  # MAINTENANCE_MODE
}
